# fmt: off
# Area: Shire
# Source: QuickMUD/ROM 2.4
# VNUM ranges: 1100-1199
# Credits: { 5 35} Poohb   The Shire


AREA = {
    "name":     'Shire',
    "builders": '{ 5 35} Poohb   The Shire',
    "vnums":    (1100, 1199),
    "credits":  '{ 5 35} Poohb   The Shire',
    "levels":   (5, 35),
}

# -- Room VNUMs -----------------------------------------------------------------
R_DIMLY_LIT_PATH                   = 1100
R_DIMLY_LIT_PATH_1101              = 1101
R_DIMLY_LIT_PATH_1102              = 1102
R_ENTRANCE_TO_THE_SHIRE            = 1103
R_BYWATER_ROAD                     = 1104
R_GENERAL_STORE                    = 1105
R_BYWATER_ROAD_1106                = 1106
R_HOUSE_OF_ARMS                    = 1107
R_KID_N_KEEP                       = 1108
R_BEND_IN_THE_ROAD                 = 1109
R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE = 1110
R_THAIN_S_OFFICE                   = 1111
R_BYWATER_ROAD_1112                = 1112
R_BYWATER_ROAD_1113                = 1113
R_SMIAL                            = 1114
R_SMIAL_1115                       = 1115
R_IVY_BUSH                         = 1116
R_SHIRIFF_TRAINING_GROUNDS         = 1117
R_BYWATER_ROAD_1118                = 1118
R_SHIRIFF_POST_OF_THE_BRIDGE       = 1119
R_BYWATER_ROAD_1120                = 1120
R_GROCER_S_DELIGHT                 = 1121
R_BYWATER_ROAD_1122                = 1122
R_ENTRANCE_TO_WATERMILL            = 1123
R_WATERMILL                        = 1124
R_REAR_OF_WATERMILL                = 1125
R_TOOK_HILL                        = 1126
R_NORTHERN_END_OF_GRASSY_FIELD     = 1127
R_GRASSY_FIELD                     = 1128
R_SOUTHERN_END_OF_GRASSY_FIELD     = 1129
R_WESTERN_END_OF_GRASSY_FIELD      = 1130
R_BRANDYWINE_BRIDGE                = 1131
R_DELVING_LANE                     = 1132
R_DELVING_LANE_1133                = 1133
R_DELVING_LANE_1134                = 1134
R_BAG_END                          = 1135
R_BEDROOM                          = 1136
R_PANTRY                           = 1137
R_GRASSY_FIELD_1138                = 1138
R_PIG_PEN                          = 1139
R_STONY_PATH                       = 1140
R_GAMGEE_RESIDENCE                 = 1141
R_BARN                             = 1142
R_CHICKEN_COOP                     = 1143
R_GREEN_DRAGON                     = 1144
R_SHIRIFF_POST_OF_DELVING_LANE     = 1145
R_DARK_TUNNEL                      = 1146
R_DARK_TUNNEL_1147                 = 1147
R_DARK_TUNNEL_1148                 = 1148
R_THREE_WAY_INTERSECTION           = 1149
R_END_OF_A_DARK_TUNNEL             = 1150
R_DARK_TUNNEL_1151                 = 1151
R_DARK_TUNNEL_1152                 = 1152
R_SHIRIFF_POST_OF_THE_LOWER_SHIRE  = 1153
R_HALFLING_HOLE                    = 1154
R_HALFLING_HOLE_1155               = 1155
R_END_OF_A_DARK_TUNNEL_1156        = 1156
R_INN_OF_THE_GREEN_DRAGON          = 1157

# -- Mob template VNUMs ---------------------------------------------------------
M_OLDSTYLE_ELVEN_WIZARD            = 1100
M_OLDSTYLE_RING_KEEPER             = 1101
M_OLDSTYLE_FARMER_GAMGEE           = 1102
M_OLDSTYLE_TODDLER                 = 1103
M_OLDSTYLE_NURSEMAID               = 1104
M_OLDSTYLE_COW                     = 1105
M_OLDSTYLE_PIG                     = 1106
M_OLDSTYLE_CHICKEN                 = 1107
M_OLDSTYLE_BULL                    = 1108
M_OLDSTYLE_HORSE                   = 1109
M_OLDSTYLE_SHIRIFF                 = 1110
M_OLDSTYLE_SHIRIFF_1111            = 1111
M_OLDSTYLE_THAIN                   = 1112
M_OLDSTYLE_INNKEEPER               = 1113
M_OLDSTYLE_MILLER                  = 1114
M_OLDSTYLE_MILL_WORKER             = 1115
M_OLDSTYLE_ELVEN_WARRIOR           = 1116
M_OLDSTYLE_DWARVEN_PRINCE          = 1117
M_OLDSTYLE_SHOPKEEPER              = 1118
M_OLDSTYLE_GROCER                  = 1119
M_OLDSTYLE_BLACKSMITH              = 1120
M_OLDSTYLE_BATTLE_MASTER           = 1121
M_OLDSTYLE_HALFLING_YOUTH          = 1122
M_OLDSTYLE_SEASONED_ADVENTURER     = 1123
M_OLDSTYLE_LOCAL_GOSSIP            = 1124
M_OLDSTYLE_HALFLING_BEAUTY         = 1125
M_OLDSTYLE_TRAINEE                 = 1126
M_OLDSTYLE_CHIC_URBANITE           = 1127
M_OLDSTYLE_COUNTRY_BUMPKIN         = 1128
M_OLDSTYLE_INNKEEPER_1130          = 1130
M_OLDSTYLE_RECEPTIONIST            = 1131
M_OLDSTYLE_SHIRIFF_1132            = 1132

# -- Item template VNUMs --------------------------------------------------------
I_RAINBOW_STAFF                    = 1100
I_STING                            = 1101
I_SIGN                             = 1102
I_PIPEWEED_BREAD                   = 1103
I_SILVERY_CLOAK                    = 1104
I_ONE_RING                         = 1105
I_ELVEN_SPEAR                      = 1106
I_MITHRIL_AXE                      = 1107
I_THAIN_GIRTH                      = 1108
I_TINY_DAGGER                      = 1109
I_EGG                              = 1110
I_BAG                              = 1111
I_LANTERN                          = 1112
I_BARDICHE                         = 1113
I_FLAIL                            = 1114
I_WOODEN_BARDICHE                  = 1115
I_DAGGER_SHIRIFF                   = 1116
I_CLUB_HEAVY                       = 1117

# -- Mob templates --------------------------------------------------------------
# hp_dice / mana_dice / damage: (num_dice, die_size, bonus)
# armor: (pierce, bash, slash, exotic), raw .are units
# hitroll: from mob level line
MOBILES = {
    M_OLDSTYLE_ELVEN_WIZARD: {
        "keywords":    'oldstyle elven wizard',
        "short_descr": 'the Elven Wizard',
        "long_descr":  'An Elven Wizard is here, creating fireworks for the festivities.',
        "description": 'The Elven Wizard looks at you in a solemn sort of way.  His gaze seems to\npenetrate through your innermost being.  He is wearing a silvery cloak\nand holding a multi-colored staff.  Although he appears to be older\nthan the oldest man, he seems to have an inner strength which most mortals\ncannot overcome.',
        "race":        'human',
        "act_flags": {"sentinel": True, "stay_area": True, "mage": True},
        "affected_by": {"detect_invis": True},
        "alignment": 500,
        "level":     18,
        "hitroll":   0,
        "hp_dice":   (3, 9, 258),
        "mana_dice": (18, 9, 100),
        "damage":    (2, 6, 3),  "dam_type": 'none',
        "armor":     (-3, -3, -3, 4),
        "off_flags": {"dodge": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 105,
        "size":   'medium',
    },
    M_OLDSTYLE_RING_KEEPER: {
        "keywords":    'oldstyle ring keeper',
        "short_descr": 'the Keeper of the Ring',
        "long_descr":  'The Keeper of the Ring is here, guarding his treasure jealously.',
        "description": 'The Ring Keeper is a rather big but short halfling.  His short stature and\nbulbous nose belie his true nature.  An elven sword that glows with a blue\nlight hangs from his belt, and on his finger you see the One Ring.  Although\nusually a halfling of peace, he will fight you to the death if you attempt\nto take away that which belongs to him.',
        "race":        'human',
        "act_flags": {"sentinel": True, "stay_area": True, "thief": True},
        "affected_by": {"invisible": True, "detect_invis": True, "detect_hidden": True},
        "alignment": 0,
        "level":     20,
        "hitroll":   0,
        "hp_dice":   (3, 9, 308),
        "mana_dice": (10, 9, 100),
        "damage":    (2, 7, 5),  "dam_type": 'none',
        "armor":     (-4, -4, -4, 6),
        "off_flags": {"backstab": True, "disarm": True, "dodge": True, "kick_dirt": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 61,
        "size":   'medium',
    },
    M_OLDSTYLE_FARMER_GAMGEE: {
        "keywords":    'oldstyle farmer gamgee',
        "short_descr": 'Farmer Gamgee',
        "long_descr":  'Farmer Gamgee sniffs the air, wondering if harvest time is near.',
        "description": "Farmer Gamgee is a short, stout halfling of thirty years.  His skin has\nbeen tanned from working the fields night and day.  He's quite a jolly\nchap, always ready to befriend an injured bunny rabbit.",
        "race":        'human',
        "act_flags": {"sentinel": True, "wimpy": True},
        "alignment": 350,
        "level":     7,
        "hitroll":   0,
        "hp_dice":   (2, 6, 85),
        "mana_dice": (3, 9, 100),
        "damage":    (1, 8, 1),  "dam_type": 'none',
        "armor":     (4, 4, 4, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'rest',
        "default_pos": 'rest',
        "material": '0',
        "sex":    'male',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_TODDLER: {
        "keywords":    'oldstyle toddler',
        "short_descr": 'a toddler',
        "long_descr":  'A toddler crawls about, looking for something to chew on.',
        "description": 'The toddler is dressed in nothing but his birthday suit.  He crawls about\nfor he hasn\'t learned to walk yet.  He peers up at you and asks "da da?"',
        "race":        'human',
        "act_flags": {"sentinel": True, "wimpy": True},
        "alignment": 100,
        "level":     2,
        "hitroll":   0,
        "hp_dice":   (2, 7, 21),
        "mana_dice": (1, 9, 100),
        "damage":    (1, 5, 0),  "dam_type": 'none',
        "armor":     (8, 8, 8, 10),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_NURSEMAID: {
        "keywords":    'oldstyle nursemaid',
        "short_descr": 'a nursemaid',
        "long_descr":  'A nursemaid wanders about, trying to keep track of all the toddlers.',
        "description": 'The nursemaid looks rather tired and worn out.  Taking care of so many\ntoddlers for too long has evidently taken its toll.  She looks to you and\nin her eyes you can see her longing for a better life.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 100,
        "level":     5,
        "hitroll":   0,
        "hp_dice":   (2, 6, 60),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 6, 1),  "dam_type": 'none',
        "armor":     (5, 5, 5, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'female',
        "wealth": 1,
        "size":   'medium',
    },
    M_OLDSTYLE_COW: {
        "keywords":    'oldstyle cow',
        "short_descr": 'a cow',
        "long_descr":  'A cow is here, chewing her cud.',
        "description": "The cow looks like it hasn't been milked in quite some time.  Although she\nis past her prime, you see that she still has a lot of years left, and that\nif provoked, her rear kick can be quite deadly.",
        "race":        'human',
        "act_flags": {"stay_area": True, "pet": True},
        "alignment": 0,
        "level":     4,
        "hitroll":   0,
        "hp_dice":   (2, 7, 46),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 5, 1),  "dam_type": 'none',
        "armor":     (6, 6, 6, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'rest',
        "default_pos": 'rest',
        "material": '0',
        "sex":    'none',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_PIG: {
        "keywords":    'oldstyle pig',
        "short_descr": 'a pig',
        "long_descr":  'A pig wallows in the mud and oinks in contentment.',
        "description": 'The pig appears quite happy to be a pig.  He is oblivious to your presence\nand cares only for the care-free life that he leads.  It is enormously fat\nand consequently cannot move around very quickly.',
        "race":        'pig',
        "act_flags": {"stay_area": True, "pet": True},
        "alignment": 0,
        "level":     3,
        "hitroll":   0,
        "hp_dice":   (2, 6, 35),
        "mana_dice": (1, 9, 100),
        "damage":    (1, 6, 0),  "dam_type": 'none',
        "armor":     (7, 7, 7, 10),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_race": True},
        "start_pos":   'rest',
        "default_pos": 'rest',
        "material": '0',
        "sex":    'none',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_CHICKEN: {
        "keywords":    'oldstyle chicken',
        "short_descr": 'a chicken',
        "long_descr":  'A chicken sits on her nest.',
        "description": 'The chicken is bright and healthy.  She has no weapons but her beak.',
        "race":        'human',
        "act_flags": {"stay_area": True, "pet": True},
        "alignment": 0,
        "level":     2,
        "hitroll":   0,
        "hp_dice":   (2, 7, 21),
        "mana_dice": (1, 9, 100),
        "damage":    (1, 5, 0),  "dam_type": 'none',
        "armor":     (8, 8, 8, 10),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'female',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_BULL: {
        "keywords":    'oldstyle bull',
        "short_descr": 'a bull',
        "long_descr":  'A bull scratches at the ground and lowers his head.',
        "description": 'The bull is in top condition.  He looks like quite a fighter, nothing to be\nreckoned with.  With his horns and his hooves he can attack just about\nanything.',
        "race":        'human',
        "act_flags": {"sentinel": True, "aggressive": True},
        "alignment": 0,
        "level":     6,
        "hitroll":   0,
        "hp_dice":   (2, 7, 71),
        "mana_dice": (3, 9, 100),
        "damage":    (1, 7, 1),  "dam_type": 'none',
        "armor":     (4, 4, 4, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_HORSE: {
        "keywords":    'oldstyle horse',
        "short_descr": 'a horse',
        "long_descr":  'A horse becomes frightened by your presence.',
        "description": 'The horse looks at you and turns away.  You can tell that it is afraid of you.',
        "race":        'human',
        "act_flags": {"sentinel": True, "stay_area": True, "pet": True},
        "alignment": 0,
        "level":     4,
        "hitroll":   0,
        "hp_dice":   (2, 7, 46),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 5, 1),  "dam_type": 'none',
        "armor":     (6, 6, 6, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'none',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_SHIRIFF: {
        "keywords":    'oldstyle shiriff',
        "short_descr": 'a shiriff',
        "long_descr":  'A shiriff of the Shire looks for signs of trouble.',
        "description": "The shiriff is over waist high, quite tall for a halfling.  His eyes are\never roaming, looking for signs of trouble from riff-raff like you.  In\nhis belt is a thin dagger, and on his body he wears a suit of leather armor.\nThis is one halfling you don't want to mess with.",
        "race":        'human',
        "act_flags": {"scavenger": True, "stay_area": True, "warrior": True},
        "alignment": 150,
        "level":     8,
        "hitroll":   0,
        "hp_dice":   (2, 6, 110),
        "mana_dice": (4, 9, 100),
        "damage":    (1, 7, 2),  "dam_type": 'none',
        "armor":     (3, 3, 3, 9),
        "off_flags": {"bash": True, "berserk": True, "disarm": True, "kick": True, "parry": True, "rescue": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 2,
        "size":   'medium',
    },
    M_OLDSTYLE_SHIRIFF_1111: {
        "keywords":    'oldstyle shiriff',
        "short_descr": 'a shiriff',
        "long_descr":  'A shiriff of the Shire looks for signs of trouble.',
        "description": "The shiriff is over waist high, quite tall for a halfling.  His eyes are\never roaming, looking for signs of trouble from riff raff like you.  In\nhis belt is a thin dagger, and on his body he wears a suit of leather armor.\nThis is one halfling you don't want to mess with.",
        "race":        'human',
        "act_flags": {"scavenger": True, "stay_area": True, "warrior": True},
        "alignment": 150,
        "level":     8,
        "hitroll":   0,
        "hp_dice":   (2, 6, 110),
        "mana_dice": (4, 9, 100),
        "damage":    (1, 7, 2),  "dam_type": 'none',
        "armor":     (3, 3, 3, 9),
        "off_flags": {"bash": True, "berserk": True, "disarm": True, "kick": True, "parry": True, "rescue": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 2,
        "size":   'medium',
    },
    M_OLDSTYLE_THAIN: {
        "keywords":    'oldstyle thain',
        "short_descr": 'the Thain',
        "long_descr":  'The Thain commands respect from all Shire folk.',
        "description": "A personable yet serious halfling, the Thain looks at you and yells a\ndeep 'Hullo'.  He walks about comfortably, secure in the knowledge that\nas long as he's in office, the Shire will always remain a safe haven for\nShire folk.",
        "race":        'human',
        "act_flags": {"stay_area": True, "warrior": True},
        "alignment": 400,
        "level":     14,
        "hitroll":   0,
        "hp_dice":   (3, 9, 208),
        "mana_dice": (7, 9, 100),
        "damage":    (1, 12, 3),  "dam_type": 'none',
        "armor":     (-1, -1, -1, 8),
        "off_flags": {"bash": True, "berserk": True, "disarm": True, "kick": True, "parry": True, "rescue": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 25,
        "size":   'medium',
    },
    M_OLDSTYLE_INNKEEPER: {
        "keywords":    'oldstyle innkeeper',
        "short_descr": 'the Innkeeper',
        "long_descr":  'The Innkeeper stands here awaiting your order.',
        "description": 'The Innkeeper is a jolly old halfling who spends his days eavesdropping on\nlocal gossip.  In his younger days, he was quite a seasoned traveller.',
        "race":        'human',
        "act_flags": {"sentinel": True, "stay_area": True},
        "alignment": 200,
        "level":     12,
        "hitroll":   0,
        "hp_dice":   (2, 10, 150),
        "mana_dice": (6, 9, 100),
        "damage":    (1, 10, 3),  "dam_type": 'none',
        "armor":     (0, 0, 0, 8),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 35,
        "size":   'medium',
    },
    M_OLDSTYLE_MILLER: {
        "keywords":    'oldstyle miller',
        "short_descr": 'the Miller',
        "long_descr":  'The Miller is here, overseeing his busy mill workers.',
        "description": 'The Miller is an impatient young halfling, always trying to command more\nrespect from his workers than he can get.  He looks like the type of person\nwho deserves a spanking but never got one.',
        "race":        'human',
        "act_flags": {"scavenger": True, "stay_area": True, "wimpy": True},
        "alignment": 50,
        "level":     6,
        "hitroll":   0,
        "hp_dice":   (2, 7, 71),
        "mana_dice": (3, 9, 100),
        "damage":    (1, 7, 1),  "dam_type": 'none',
        "armor":     (4, 4, 4, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 10,
        "size":   'medium',
    },
    M_OLDSTYLE_MILL_WORKER: {
        "keywords":    'oldstyle mill worker',
        "short_descr": 'the mill worker',
        "long_descr":  'The mill worker runs to and fro.',
        "description": "The mill worker is in fine shape from the hard labor that he does at the\nmill.  He doesn't notice your presence, but he looks like he could break you\nin two without thinking about it.",
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 0,
        "level":     5,
        "hitroll":   0,
        "hp_dice":   (2, 6, 60),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 6, 1),  "dam_type": 'none',
        "armor":     (5, 5, 5, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 2,
        "size":   'medium',
    },
    M_OLDSTYLE_ELVEN_WARRIOR: {
        "keywords":    'oldstyle elven warrior',
        "short_descr": 'the elven warrior',
        "long_descr":  'The elven warrior watches you solemnly.',
        "description": 'The tall elven warrior is light and fair-skinned.  The expression that he wears\non his countenance is solemn and tragic.  He cares not for this world any\nlonger and wearies of it.',
        "race":        'human',
        "act_flags": {"sentinel": True, "mage": True},
        "alignment": 600,
        "level":     17,
        "hitroll":   0,
        "hp_dice":   (3, 9, 233),
        "mana_dice": (17, 9, 100),
        "damage":    (1, 12, 3),  "dam_type": 'none',
        "armor":     (-2, -2, -2, 4),
        "off_flags": {"dodge": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 25,
        "size":   'medium',
    },
    M_OLDSTYLE_DWARVEN_PRINCE: {
        "keywords":    'oldstyle dwarven prince',
        "short_descr": 'the dwarven prince',
        "long_descr":  'The dwarven prince sits here patiently for the return of his king.',
        "description": 'Grim and cold, the dwarven prince is quite strong and bulky, even for the\ndwarves of his land.  His glowing eyes peer out of his bushy face and stare\nbeyond your gaze.',
        "race":        'human',
        "act_flags": {"sentinel": True, "cleric": True},
        "alignment": 200,
        "level":     17,
        "hitroll":   0,
        "hp_dice":   (3, 9, 258),
        "mana_dice": (17, 9, 100),
        "damage":    (2, 6, 4),  "dam_type": 'none',
        "armor":     (-3, -3, -3, 6),
        "off_flags": {"disarm": True, "kick": True, "parry": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 35,
        "size":   'medium',
    },
    M_OLDSTYLE_SHOPKEEPER: {
        "keywords":    'oldstyle shopkeeper',
        "short_descr": 'the shopkeeper',
        "long_descr":  'The shopkeeper smiles and patiently waits for you to buy something.',
        "description": 'The shopkeeper will fight like a madman to protect his store from riff-raff\nlike you.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 600,
        "level":     21,
        "hitroll":   0,
        "hp_dice":   (4, 10, 360),
        "mana_dice": (10, 9, 100),
        "damage":    (4, 4, 5),  "dam_type": 'none',
        "armor":     (-5, -5, -5, 7),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 600,
        "size":   'medium',
    },
    M_OLDSTYLE_GROCER: {
        "keywords":    'oldstyle grocer',
        "short_descr": 'the grocer',
        "long_descr":  'The grocer offers you the finest breads in all the land.',
        "description": "The grocer is a large, jovial halfling who knows how to enjoy his pipeweed.\nHowever, he also knows that it's worth protecting and so will do everything\nin his power to prevent riff-raff like you from stealing it.",
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 600,
        "level":     21,
        "hitroll":   0,
        "hp_dice":   (4, 10, 360),
        "mana_dice": (10, 9, 100),
        "damage":    (4, 4, 5),  "dam_type": 'none',
        "armor":     (-5, -5, -5, 7),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 75,
        "size":   'medium',
    },
    M_OLDSTYLE_BLACKSMITH: {
        "keywords":    'oldstyle blacksmith',
        "short_descr": 'the blacksmith',
        "long_descr":  'The blacksmith bids you welcome to his humble store.',
        "description": 'The blacksmith is a lean and mean fighting machine.  His knowledge of weapons\nand armour would certainly help him in any fight against riff-raff like you.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 600,
        "level":     50,
        "hitroll":   0,
        "hp_dice":   (50, 10, 4500),
        "mana_dice": (25, 9, 100),
        "damage":    (5, 8, 19),  "dam_type": 'none',
        "armor":     (-20, -20, -20, 3),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 900,
        "size":   'medium',
    },
    M_OLDSTYLE_BATTLE_MASTER: {
        "keywords":    'oldstyle battle master',
        "short_descr": 'the battle master',
        "long_descr":  'The battle master offers you the services of his fine trainees.',
        "description": 'The battle master is a wizened fighter, with many scars to prove his worth.',
        "race":        'human',
        "act_flags": {"sentinel": True, "warrior": True},
        "alignment": 350,
        "level":     25,
        "hitroll":   0,
        "hp_dice":   (5, 10, 600),
        "mana_dice": (12, 9, 100),
        "damage":    (2, 10, 7),  "dam_type": 'none',
        "armor":     (-7, -7, -7, 6),
        "off_flags": {"bash": True, "berserk": True, "disarm": True, "kick": True, "parry": True, "rescue": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 75,
        "size":   'medium',
    },
    M_OLDSTYLE_HALFLING_YOUTH: {
        "keywords":    'oldstyle halfling youth',
        "short_descr": 'a halfling youth',
        "long_descr":  'A halfling youth stands here, waiting for nothing in particular.',
        "description": "The halfling youth is not yet quite in the prime of his youth.  He's knee\nhigh and you get the sudden urge to step on him.",
        "race":        'human',
        "act_flags": {"stay_area": True, "wimpy": True, "thief": True},
        "affected_by": {"detect_invis": True, "detect_hidden": True},
        "alignment": 0,
        "level":     3,
        "hitroll":   0,
        "hp_dice":   (2, 7, 21),
        "mana_dice": (1, 9, 100),
        "damage":    (1, 5, 0),  "dam_type": 'none',
        "armor":     (8, 8, 8, 10),
        "off_flags": {"backstab": True, "disarm": True, "dodge": True, "kick_dirt": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_SEASONED_ADVENTURER: {
        "keywords":    'oldstyle seasoned adventurer',
        "short_descr": 'a seasoned adventurer',
        "long_descr":  'A seasoned adventurer sits here, telling tales of fame and fortune.',
        "description": 'The seasoned adventurer has seen his share of glory days.  Although he is\npast his prime, he still looks like he could put up more than his share of\na good fight.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 100,
        "level":     8,
        "hitroll":   0,
        "hp_dice":   (2, 7, 96),
        "mana_dice": (4, 9, 100),
        "damage":    (1, 7, 2),  "dam_type": 'none',
        "armor":     (3, 3, 3, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 8,
        "size":   'medium',
    },
    M_OLDSTYLE_LOCAL_GOSSIP: {
        "keywords":    'oldstyle local gossip',
        "short_descr": 'a local gossip',
        "long_descr":  'A local gossip asks you, "Have you heard the latest?"',
        "description": "The gossip is all talk and no action.  You're transfixed by her ability to\ntalk so much so quickly.",
        "race":        'human',
        "act_flags": {"sentinel": True, "wimpy": True},
        "alignment": 0,
        "level":     4,
        "hitroll":   0,
        "hp_dice":   (2, 7, 46),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 5, 1),  "dam_type": 'none',
        "armor":     (6, 6, 6, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'female',
        "wealth": 1,
        "size":   'medium',
    },
    M_OLDSTYLE_HALFLING_BEAUTY: {
        "keywords":    'oldstyle halfling beauty',
        "short_descr": 'a halfling beauty',
        "long_descr":  'A halfling beauty stares dreamily into your eyes.',
        "description": "She is the most beautiful creature you've seen in quite some time.  As you\nstare at her, thoughts of all else vanish.  You get the sudden urge to grovel\nat her feet, hoping she'll take you in like a lost puppy.  You wouldn't dare\nharm a hair on her precious little head.",
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 1000,
        "level":     6,
        "hitroll":   0,
        "hp_dice":   (2, 7, 71),
        "mana_dice": (3, 9, 100),
        "damage":    (1, 7, 1),  "dam_type": 'none',
        "armor":     (4, 4, 4, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'female',
        "wealth": 3,
        "size":   'medium',
    },
    M_OLDSTYLE_TRAINEE: {
        "keywords":    'oldstyle trainee',
        "short_descr": 'a trainee',
        "long_descr":  'A trainee screams a death cry as he delivers the fatal blow to a dummy.',
        "description": "The trainee smiles smugly, aware of your interest in him.  He's a little\nfresh, but his enthusiasm and desire to please more than make up for what\nhe lacks in skill.",
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 0,
        "level":     5,
        "hitroll":   0,
        "hp_dice":   (2, 6, 60),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 6, 1),  "dam_type": 'none',
        "armor":     (5, 5, 5, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 0,
        "size":   'medium',
    },
    M_OLDSTYLE_CHIC_URBANITE: {
        "keywords":    'oldstyle chic urbanite',
        "short_descr": 'a chic urbanite',
        "long_descr":  'A chic urbanite sits here, enjoying his class status.',
        "description": "The urbanite seems very much at home in his surroundings.  His clothes are\nall of the latest fashions and his manners impeccable.  He offers you some\ncoins if you'd be so good as to order a drink for him.",
        "race":        'human',
        "act_flags": {"sentinel": True, "wimpy": True},
        "alignment": 0,
        "level":     4,
        "hitroll":   0,
        "hp_dice":   (2, 7, 46),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 5, 1),  "dam_type": 'none',
        "armor":     (6, 6, 6, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'sit',
        "default_pos": 'sit',
        "material": '0',
        "sex":    'male',
        "wealth": 5,
        "size":   'medium',
    },
    M_OLDSTYLE_COUNTRY_BUMPKIN: {
        "keywords":    'oldstyle country bumpkin',
        "short_descr": 'a country bumpkin',
        "long_descr":  'A country bumpkin dreams of pipeweed and its many uses.',
        "description": 'The country bumpkin snores noisily.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 0,
        "level":     5,
        "hitroll":   0,
        "hp_dice":   (2, 6, 60),
        "mana_dice": (2, 9, 100),
        "damage":    (1, 6, 1),  "dam_type": 'none',
        "armor":     (5, 5, 5, 9),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'sleep',
        "default_pos": 'sleep',
        "material": '0',
        "sex":    'male',
        "wealth": 3,
        "size":   'medium',
    },
    M_OLDSTYLE_INNKEEPER_1130: {
        "keywords":    'oldstyle innkeeper',
        "short_descr": 'the Innkeeper',
        "long_descr":  'The Innkeeper stands here awaiting your order.',
        "description": 'The Innkeeper is a jolly old halfling who spends his days eavesdropping on\nlocal gossip.  In his younger days, he was quite a seasoned traveller.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 200,
        "level":     12,
        "hitroll":   0,
        "hp_dice":   (2, 10, 150),
        "mana_dice": (6, 9, 100),
        "damage":    (1, 10, 3),  "dam_type": 'none',
        "armor":     (0, 0, 0, 8),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 50,
        "size":   'medium',
    },
    M_OLDSTYLE_RECEPTIONIST: {
        "keywords":    'oldstyle receptionist',
        "short_descr": 'the receptionist',
        "long_descr":  'The receptionist sits here, signing forms.',
        "description": 'He is a very professional looking type.',
        "race":        'human',
        "act_flags": {"sentinel": True},
        "alignment": 200,
        "level":     12,
        "hitroll":   0,
        "hp_dice":   (2, 10, 150),
        "mana_dice": (6, 9, 100),
        "damage":    (1, 10, 3),  "dam_type": 'none',
        "armor":     (0, 0, 0, 8),
        "off_flags": {"disarm": True, "dodge": True, "trip": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 3,
        "size":   'medium',
    },
    M_OLDSTYLE_SHIRIFF_1132: {
        "keywords":    'oldstyle shiriff',
        "short_descr": 'a shiriff',
        "long_descr":  'A shiriff of the Shire looks for the lost halfling youth.',
        "description": 'The shiriff is over waist high, quite tall for a halfling.\nHe looks at you, smiles and asks you if you have seen a halfling youth\nsomewhere outside the shire.',
        "race":        'human',
        "act_flags": {"sentinel": True, "warrior": True},
        "alignment": 150,
        "level":     8,
        "hitroll":   0,
        "hp_dice":   (2, 6, 110),
        "mana_dice": (4, 9, 100),
        "damage":    (1, 7, 2),  "dam_type": 'none',
        "armor":     (3, 3, 3, 9),
        "off_flags": {"bash": True, "berserk": True, "disarm": True, "kick": True, "parry": True, "rescue": True, "assist_vnum": True},
        "start_pos":   'stand',
        "default_pos": 'stand',
        "material": '0',
        "sex":    'male',
        "wealth": 2,
        "size":   'medium',
    },
}

# -- Specials -------------------------------------------------------------------
# ("M", mob_vnum, spec_fun_name) -- assign special function to mob template
SPECIALS = (
    ("M", M_OLDSTYLE_ELVEN_WIZARD, 'spec_cast_mage'),
    ("M", M_OLDSTYLE_RING_KEEPER, 'spec_thief'),
    ("M", M_OLDSTYLE_SHIRIFF, 'spec_guard'),
    ("M", M_OLDSTYLE_SHIRIFF_1111, 'spec_guard'),
    ("M", M_OLDSTYLE_THAIN, 'spec_guard'),
    ("M", M_OLDSTYLE_ELVEN_WARRIOR, 'spec_cast_mage'),
    ("M", M_OLDSTYLE_DWARVEN_PRINCE, 'spec_cast_cleric'),
    ("M", M_OLDSTYLE_BATTLE_MASTER, 'spec_guard'),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 'spec_thief'),
    ("M", M_OLDSTYLE_SHIRIFF_1132, 'spec_guard'),
)

# -- Rooms ----------------------------------------------------------------------
ROOMS = {
    R_DIMLY_LIT_PATH: {
        "name": 'A dimly lit path',
        "desc": 'You tread through the deep, dark forest on a dimly lit path.  Up ahead you\ncan hear the faint sounds of a village.',
        "exits": {
            "n": {"to": R_DIMLY_LIT_PATH_1101, "desc": 'The dimly lit path leads north through the dense forest.'},
            "s": {"to": 6000, "desc": 'The dimly lit path leads south through the light forest.'},
        },
        "sector": 'forest',
    },
    R_DIMLY_LIT_PATH_1101: {
        "name": 'A dimly lit path',
        "desc": 'You tread through the deep, dark forest on a dimly lit path.  Up ahead you\ncan hear the faint sounds of a village.',
        "exits": {
            "n": {"to": R_DIMLY_LIT_PATH_1102, "desc": 'The dimly lit path leads north through the dense forest.'},
            "s": {"to": R_DIMLY_LIT_PATH, "desc": 'The dimly lit path leads south through the dense forest.'},
        },
        "sector": 'forest',
    },
    R_DIMLY_LIT_PATH_1102: {
        "name": 'A dimly lit path',
        "desc": 'You tread through the deep, dark forest on a dimly lit path.  The forest\nhere seems less dense than to the south.  Northward you see the faint outline\nof a village.',
        "exits": {
            "n": {"to": R_ENTRANCE_TO_THE_SHIRE, "desc": 'The dimly lit path leads to a village.'},
            "s": {"to": R_DIMLY_LIT_PATH_1101, "desc": 'The dimly lit path leads south through the dense forest.'},
        },
        "sector": 'forest',
    },
    R_ENTRANCE_TO_THE_SHIRE: {
        "name": 'Entrance to the Shire',
        "desc": 'You stand at the entrance to the Shire.  You see halflings, no more than\nwee tall, every which way you look. Bywater Road leads east and west.',
        "exits": {
            "e": {"to": R_BYWATER_ROAD, "desc": 'To the east runs Bywater Road.'},
            "s": {"to": R_DIMLY_LIT_PATH_1102, "desc": 'To the south you see a dimly lit path which leads to a dense forest.'},
            "w": {"to": R_BYWATER_ROAD_1118, "desc": 'To the west runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_BYWATER_ROAD: {
        "name": 'Bywater Road',
        "desc": 'You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the east and west while to the north lies the general store.',
        "exits": {
            "n": {"to": R_GENERAL_STORE, "desc": 'The general store lies to the north.'},
            "e": {"to": R_BYWATER_ROAD_1106, "desc": 'To the east runs Bywater Road.'},
            "w": {"to": R_ENTRANCE_TO_THE_SHIRE, "desc": 'To the west you see the entrance to the Shire.'},
        },
        "sector": 'city',
    },
    R_GENERAL_STORE: {
        "name": 'The General Store',
        "desc": 'You are inside the general store.  All sorts of goodies are stacked on the\nmany shelves.  Your local friendly shopkeeper is smiling patiently, waiting to\nserve you to the best of his abilities.  The only exit is to the south.',
        "exits": {
            "s": {"to": R_BYWATER_ROAD, "desc": 'The only exit lies to the south.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BYWATER_ROAD_1106: {
        "name": 'Bywater Road',
        "desc": 'You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the east and west.  To the north, steps lead to a friendly looking\nweaponry/armory while a nursery lies to the south.',
        "exits": {
            "n": {"to": R_HOUSE_OF_ARMS, "desc": 'Steps lead to a friendly looking weaponry and armory.'},
            "e": {"to": R_BEND_IN_THE_ROAD, "desc": 'To the east runs Bywater Road.'},
            "s": {"to": R_KID_N_KEEP, "desc": "To the south lies Kid'n Keep, the local nursery."},
            "w": {"to": R_BYWATER_ROAD, "desc": 'To the west runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_HOUSE_OF_ARMS: {
        "name": 'The House of Arms',
        "desc": 'You are inside the finest weapons and armour shop in all of Shiredom.  The\nshopkeeper proudly displays his fine wares and humbly offers the best daggers\nthat you have ever laid eyes on.',
        "exits": {
            "s": {"to": R_BYWATER_ROAD_1106, "desc": 'The only exit lies to the south.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_KID_N_KEEP: {
        "name": "Kid'n Keep",
        "desc": "You are inside Kid'n Keep, the convenient one-stop nursery that maintains\nthe youth of the Shire.  Toddlers run every which way while their nursemaids\nsigh in exasperation.  The only exit lies to the north.",
        "exits": {
            "n": {"to": R_BYWATER_ROAD_1106, "desc": 'The only exit lies to the north.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BEND_IN_THE_ROAD: {
        "name": 'A bend in the road',
        "desc": 'Bywater Road continues west and south.  A large, imposing building lies\nto the east.  Farther to the south, you can see an Inn of some sort.',
        "exits": {
            "e": {"to": R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE, "desc": "A large, imposing building lies to the east.  A sign reads 'Shiriff Post'."},
            "s": {"to": R_BYWATER_ROAD_1112, "desc": 'To the south runs Bywater Road.'},
            "w": {"to": R_BYWATER_ROAD_1106, "desc": 'To the west runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE: {
        "name": 'Shiriff Post of the Eastern Shire',
        "desc": 'You are in the Shiriff Post which acts as the nucleus for the three shiriffs\nof the Eastern Shire.  As you examine the shiriffs on duty, you come to realize\nthat the halflings of the Shire are not to be reckoned with.  You cower with\nawe.  A door offers passage to the east.',
        "exits": {
            "e": {"to": R_THAIN_S_OFFICE, "desc": 'A door offers passage to the office of the Thain.', "keyword": 'door', "isdoor": True},
            "w": {"to": R_BEND_IN_THE_ROAD, "desc": 'To the west you can see Bywater Road.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_THAIN_S_OFFICE: {
        "name": "Thain's Office",
        "desc": 'You stand inside the office of the Thain, the police protectorate of the\ngreat Shire.  The Thain has sworn to protect the Shire from all thieves and\nmurderers with his life, and so eyes you suspiciously.  A door to the west\nleads to the Shiriff Post.',
        "exits": {
            "w": {"to": R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE, "desc": 'A door offers passage to the Shiriff Post.', "keyword": 'door', "isdoor": True},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BYWATER_ROAD_1112: {
        "name": 'Bywater Road',
        "desc": 'You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the north and south.  To the east you spy the training grounds for\nshiriffs in training.',
        "exits": {
            "n": {"to": R_BEND_IN_THE_ROAD, "desc": 'To the north runs Bywater Road.'},
            "e": {"to": R_SHIRIFF_TRAINING_GROUNDS, "desc": 'The Shiriff Training Grounds lies to the east.'},
            "s": {"to": R_BYWATER_ROAD_1113, "desc": 'To the south runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_BYWATER_ROAD_1113: {
        "name": 'Bywater Road',
        "desc": 'You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the north.  The private residences of Shire inhabitants are to\nthe east and west while to the south lies the Ivy Bush, second only to the\nGreen Dragon for its hospitality and service.',
        "exits": {
            "n": {"to": R_BYWATER_ROAD_1112, "desc": 'To the north runs Bywater Road.'},
            "e": {"to": R_SMIAL_1115, "desc": 'You spy the private dwelling of a Shire folk to the east.'},
            "s": {"to": R_IVY_BUSH, "desc": 'To the south you see the Ivy Bush, a favorite haunt of Shire urbanites and\nseasoned travelers.'},
            "w": {"to": R_SMIAL, "desc": 'You spy the private dwelling of a Shire folk to the west.'},
        },
        "sector": 'city',
    },
    R_SMIAL: {
        "name": 'A smial',
        "desc": 'You are inside a smial, a hole in the ground which serves as the proper\ndwelling place for halflings.  As you look around this private abode, you feel\nas if you were intruding and so quickly cover your eyes.  The only exit lies\nto the east.',
        "exits": {
            "e": {"to": R_BYWATER_ROAD_1113, "desc": 'The only exit lies to the east.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_SMIAL_1115: {
        "name": 'A smial',
        "desc": 'You are inside a smial, a hole in the ground which serves as the proper\ndwelling place for halflings.  As you look around this private abode, you feel\nas if you were intruding and so quickly cover your eyes.  The only exit lies\nto the west.',
        "exits": {
            "w": {"to": R_BYWATER_ROAD_1113, "desc": 'The only exit lies to the west.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_IVY_BUSH: {
        "name": 'The Ivy Bush',
        "desc": 'You are in the Ivy Bush, one of the most famous inns in all of Shiredom.\nChique Shire urbanites and seasoned travelers fill the confines of the room\nwith gay and lively talk.  A jovial innkeeper stops all that he is doing to\nawait your command.  The only exit lies to the north.',
        "exits": {
            "n": {"to": R_BYWATER_ROAD_1113, "desc": 'The only exit lies to the north.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_SHIRIFF_TRAINING_GROUNDS: {
        "name": 'Shiriff Training Grounds',
        "desc": 'The sounds of mock battle and feigned death cries fill your ears.  Every\nwhich way you turn you see halfling trainees at the prime of their youth.  A\nwizened old battle instructor meets your gaze and asks if he may be of\nservice.  The only exit lies to the west.',
        "exits": {
            "w": {"to": R_BYWATER_ROAD_1112, "desc": 'The only exit lies to the west.'},
        },
        "sector": 'inside',
    },
    R_BYWATER_ROAD_1118: {
        "name": 'Bywater Road',
        "desc": 'You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the east and west.  A large, imposing building lies to the south.\nYou catch a glimpse of the Brandywine River to the north.',
        "exits": {
            "e": {"to": R_ENTRANCE_TO_THE_SHIRE, "desc": 'To the east you see the entrance to the Shire.'},
            "s": {"to": R_SHIRIFF_POST_OF_THE_BRIDGE, "desc": "A large, imposing building lies to the south.  A sign reads 'Shiriff Post'."},
            "w": {"to": R_BYWATER_ROAD_1120, "desc": 'To the west runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_SHIRIFF_POST_OF_THE_BRIDGE: {
        "name": 'Shiriff Post of the Bridge',
        "desc": 'You are in the Shiriff Post which acts as the nucleus for the three shiriffs\nof the Bridge.  As you examine the shiriffs on duty, you come to realize that\nthe halflings of the Shire are not to be reckoned with.  You cower with awe.\nThe only exit is to the north.',
        "exits": {
            "n": {"to": R_BYWATER_ROAD_1118, "desc": 'The only exit is to the north.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BYWATER_ROAD_1120: {
        "name": 'Bywater Road',
        "desc": "You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the east and west.  To the south you spy the Grocer's Delight,\nthe premium grocer's shop in all the realm while to the north lies Brandywine\nBridge.",
        "exits": {
            "n": {"to": R_BRANDYWINE_BRIDGE, "desc": 'Brandywine Bridge offers safe passage across the tumultuous river.'},
            "e": {"to": R_BYWATER_ROAD_1118, "desc": 'To the east runs Bywater Road.'},
            "s": {"to": R_GROCER_S_DELIGHT, "desc": "You see the Grocer's Delight to the south."},
            "w": {"to": R_BYWATER_ROAD_1122, "desc": 'To the west runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_GROCER_S_DELIGHT: {
        "name": "The Grocer's Delight",
        "desc": 'You tremble with ecstasy as the tempting odors of freshly made pipeweed\nbread fill your lungs.  Rumor has it that the pipeweed bread sold here can\nrestore vitality.  You look around but find no one to take your order.\nYou then peep over the counter and discover a friendly grocer who is too\nshort to be seen over the counter.  The only exit is to the north.',
        "exits": {
            "n": {"to": R_BYWATER_ROAD_1120, "desc": 'The only exit is to the north.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BYWATER_ROAD_1122: {
        "name": 'Bywater Road',
        "desc": 'You stand on Bywater Road, the busiest street in all of Shiredom.  The road\ncontinues to the east.  A small hill lies to the west while you can see a\nwatermill to the far south.  You catch a glimpse of the Brandywine River to\nthe north.',
        "exits": {
            "e": {"to": R_BYWATER_ROAD_1120, "desc": 'To the east runs Bywater Road.'},
            "s": {"to": R_ENTRANCE_TO_WATERMILL, "desc": 'An entrance to the watermill lies to the south.'},
            "w": {"to": R_TOOK_HILL, "desc": 'A small hill to the west blocks your view.'},
        },
        "sector": 'city',
    },
    R_ENTRANCE_TO_WATERMILL: {
        "name": 'Entrance to Watermill',
        "desc": 'You stand at the entrance to a watermill.  You hear the bustle of busy\nworkers and the sound of a creaking mill.  Bywater Road is to the north while\nthe watermill continues to the south.',
        "exits": {
            "n": {"to": R_BYWATER_ROAD_1122, "desc": 'You see Bywater Road to the north.'},
            "s": {"to": R_WATERMILL, "desc": 'A watermill meets your gaze.'},
        },
        "sector": 'inside',
    },
    R_WATERMILL: {
        "name": 'The Watermill',
        "desc": 'Halfling workers are scattered everywhere, busy at work.  You see the river\nto the west and get a compelling urge to grab the nearest worker and to toss\nhim into the river.  The entrance stands to the north while a door offers\npassage to the south.',
        "exits": {
            "n": {"to": R_ENTRANCE_TO_WATERMILL, "desc": 'You see the entrance.'},
            "s": {"to": R_REAR_OF_WATERMILL, "desc": 'A wooden door leads to the rear of the watermill.', "keyword": 'door', "isdoor": True},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_REAR_OF_WATERMILL: {
        "name": 'Rear of watermill',
        "desc": 'You stand in a damp, dimly lit room.  Mildew clings to the walls and it\nappears as if you were the first person to enter the room in ages.  A barely\nvisible portal in the ground catches your eye.',
        "exits": {
            "n": {"to": R_WATERMILL, "desc": 'A watermill meets your gaze.'},
            "d": {"to": R_DARK_TUNNEL, "desc": 'A hidden portal reveals a passageway down.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_TOOK_HILL: {
        "name": 'Took Hill',
        "desc": 'You stand on top of Took Hill, named after the legendary Bandobras Took.\nYou feel honored to be standing on a hill named after your hero.  From this\nvantage point you can see all of shiredom.  You get the feeling that with\none stomp you could eliminate their great city.  You can see the outline of\nMidgaard to the far east.  Sounds of joyful celebration are heard from the\nfields west of here.  The Brandywine flows by lazily nearby.',
        "exits": {
            "e": {"to": R_BYWATER_ROAD_1122, "desc": 'To the east runs Bywater Road.'},
            "w": {"to": R_GRASSY_FIELD, "desc": 'You see a grassy field to the west.'},
        },
        "sector": 'hills',
    },
    R_NORTHERN_END_OF_GRASSY_FIELD: {
        "name": 'Northern end of grassy field',
        "desc": 'You stand in a grassy field--nothing to get too excited about.  The field\nextends toward the south and the west.  To the east you see Took Hill.',
        "exits": {
            "s": {"to": R_GRASSY_FIELD, "desc": 'You see a grassy field.'},
        },
        "sector": 'field',
    },
    R_GRASSY_FIELD: {
        "name": 'A grassy field',
        "desc": 'You stand in the center of a grassy field.  A great birthday party appears\nto be taking place.  Great tables of food are spread out and a young halfling\nbeauty offers you welcome.  You are enticed by her generosity and suggestive\nwinks.',
        "exits": {
            "n": {"to": R_NORTHERN_END_OF_GRASSY_FIELD, "desc": 'You see a grassy field.'},
            "e": {"to": R_TOOK_HILL, "desc": 'A small hill to the east blocks your view.'},
            "s": {"to": R_SOUTHERN_END_OF_GRASSY_FIELD, "desc": 'You see a grassy field.'},
            "w": {"to": R_WESTERN_END_OF_GRASSY_FIELD, "desc": 'You see a grassy field.'},
        },
        "sector": 'field',
    },
    R_SOUTHERN_END_OF_GRASSY_FIELD: {
        "name": 'Southern end of grassy field',
        "desc": 'You stand in a grassy field--nothing to get too excited about.  The field\nextends toward the north and the west.  To the east you see Took Hill.',
        "exits": {
            "n": {"to": R_GRASSY_FIELD, "desc": 'You see a grassy field.'},
        },
        "sector": 'field',
    },
    R_WESTERN_END_OF_GRASSY_FIELD: {
        "name": 'Western end of grassy field',
        "desc": 'You stand in a grassy field--nothing to get too excited about.  The field\nextends every which way but west.',
        "exits": {
            "e": {"to": R_GRASSY_FIELD, "desc": 'You see a grassy field.'},
        },
        "sector": 'field',
    },
    R_BRANDYWINE_BRIDGE: {
        "name": 'Brandywine Bridge',
        "desc": 'You stand on a solidly built bridge.  As you look down you spy gaily\ncolored fish swimming with the current of Brandywine River.  The cool water\nlooks invitingly refreshing and you get a sudden urge to strip and bathe in\nthe river, but you hear the laughter of women nearby and so resist the urge.\nDelving Lane extends to the north while Bywater Road can be seen to the south.',
        "exits": {
            "n": {"to": R_DELVING_LANE, "desc": 'You see Delving Lane.'},
            "s": {"to": R_BYWATER_ROAD_1120, "desc": 'To the south runs Bywater Road.'},
        },
        "sector": 'city',
    },
    R_DELVING_LANE: {
        "name": 'Delving Lane',
        "desc": 'Delving Lane runs north and south in this small borough of the Shire.  To\nthe south stands Brandywine Bridge.  The Green Dragon, the undisputed leader\nin the art of innkeeping, offers rest and comfort to the east.  You hear the\nbray of horses from the west.',
        "exits": {
            "n": {"to": R_DELVING_LANE_1133, "desc": 'You see Delving Lane.'},
            "e": {"to": R_GREEN_DRAGON, "desc": 'The Green Dragon offers food, drink, and above all hospitality for mere gold.'},
            "s": {"to": R_BRANDYWINE_BRIDGE, "desc": 'Brandywine Bridge offers safe passage across the tumultuous river.'},
        },
        "sector": 'city',
    },
    R_DELVING_LANE_1133: {
        "name": 'Delving Lane',
        "desc": 'Delving Lane runs north and south in this small borough of the Shire.  A\nlarge, imposing building lies to the east.  You hear the bray of horses from\nthe west.',
        "exits": {
            "n": {"to": R_DELVING_LANE_1134, "desc": 'You see Delving Lane.'},
            "e": {"to": R_SHIRIFF_POST_OF_DELVING_LANE, "desc": "A large, imposing building lies to the east.  A sign reads 'Shiriff Post'."},
            "s": {"to": R_DELVING_LANE, "desc": 'You see Delving Lane.'},
            "w": {"to": R_GRASSY_FIELD_1138, "desc": 'You see a grassy field.'},
        },
        "sector": 'city',
    },
    R_DELVING_LANE_1134: {
        "name": 'Delving Lane',
        "desc": 'Delving Lane runs north and south in this small borough of the Shire. There\nis a small house to the west, nothing to the east, and up ahead you see a round\ndoor which leads to a rather impressive abode.',
        "exits": {
            "n": {"to": R_BAG_END, "desc": "A large, magnificent house meets your steady gaze.  Above the round door a\nsign reads 'Bag End'.", "isdoor": True},
            "s": {"to": R_DELVING_LANE_1133, "desc": 'You see Delving Lane.'},
        },
        "sector": 'city',
    },
    R_BAG_END: {
        "name": 'Bag End',
        "desc": 'You stand in a comfortably well-equipped house, a palace by humble halfling\nstandards.  On the wall you see a banner which reads "Home Sweet Home".\nA solid oak door to the east leads to a pantry while you see a cozy bedroom\nto the west.',
        "exits": {
            "e": {"to": R_PANTRY, "desc": 'Through the keyhole you see what looks like a well stocked pantry.', "keyword": 'door', "isdoor": True},
            "s": {"to": R_DELVING_LANE_1134, "desc": 'You see Delving Lane.'},
            "w": {"to": R_BEDROOM, "desc": 'You see a bedroom.  It looks like the beds have recently been slept in.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BEDROOM: {
        "name": 'Bedroom',
        "desc": 'You stand in the private bedroom of Bag End.  There are two beds to the\nside, neither of which are made.  Portraits of halflings hang on the wall,\nand as you gaze upon them you come to the conclusion that the owner of\nBag End comes from a long line of distinguished halflings.  A cozy fire\nin the fireplace keeps the room warm and comfortable.',
        "exits": {
            "e": {"to": R_BAG_END, "desc": 'Through the doorway you see the main room of Bag End.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_PANTRY: {
        "name": 'Pantry',
        "desc": 'You are inside the pantry.  Shelves filled with food and drink surround\nyou on all sides.  You wonder why a halfling would need so much to eat.\nThe presence of something unseen chills you to your bones.  On the floor\nyou spy a trapdoor.',
        "exits": {
            "w": {"to": R_BAG_END, "desc": 'Beyond the door you see the main room of Bag End.', "keyword": 'door', "isdoor": True},
            "d": {"to": R_END_OF_A_DARK_TUNNEL_1156, "desc": "It's anyone's guess as to where the trapdoor leads."},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_GRASSY_FIELD_1138: {
        "name": 'A grassy field',
        "desc": 'You stand upon a grassy field.  A bull stands grazing not far away and\nout of the corner of your eye you can see him considering you.  The sound\nof animals fill the air from the north.  To the south you see a pig pen.',
        "exits": {
            "n": {"to": R_BARN, "desc": 'You see a large barn.'},
            "e": {"to": R_DELVING_LANE_1133, "desc": 'You see Delving Lane.'},
            "s": {"to": R_PIG_PEN, "desc": 'A rather large pig pen is to the south.'},
        },
        "sector": 'field',
    },
    R_PIG_PEN: {
        "name": 'Pig pen',
        "desc": 'You feel your boots sinking into the mud.  Numerous pigs roam about,\noblivious to your company.  A grassy field is to the north while you see\na small path winding to the west.',
        "exits": {
            "n": {"to": R_GRASSY_FIELD_1138, "desc": 'You see a grassy field.'},
            "w": {"to": R_STONY_PATH, "desc": 'A small path winds its way eastward.'},
        },
        "sector": 'city',
    },
    R_STONY_PATH: {
        "name": 'A stony path',
        "desc": 'You walk on a stony path which leads to a small residence to the north.\nFrom the east you hear the noisy din of pigs.',
        "exits": {
            "n": {"to": R_GAMGEE_RESIDENCE, "desc": 'To the north you see a modest house.'},
            "e": {"to": R_PIG_PEN, "desc": 'A rather large pig pen is to the east.'},
        },
        "sector": 'city',
    },
    R_GAMGEE_RESIDENCE: {
        "name": 'Gamgee Residence',
        "desc": 'You stand inside a modest home.  You deduce that this is indeed the home\nof whomever owns the surrounding lands.  The air is somewhat musty and\nthe smell reminds you of a stable.  As you look around disdainfully, you\nthink to yourself that this is more of a shack than a proper residence and\nyou long for the urban riches of the Shire proper.',
        "exits": {
            "s": {"to": R_STONY_PATH, "desc": 'You see a small path winding its way southward.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_BARN: {
        "name": 'A barn',
        "desc": "Animals of every sort fill the small barn.  You feel the hot breath of\nhorses and cows on your neck and you feel the sudden need for fresh air.\nOther than that, you feel cozy and protected and don't mind staying for a\nbit longer.  All the warmth and good vibes remind you of the days when your\nmother would hold you in her arms and sing you to sleep.  You find yourself\nwanting to cradle all the animals.",
        "exits": {
            "n": {"to": R_CHICKEN_COOP, "desc": 'You see a chicken coop to the north.'},
            "s": {"to": R_GRASSY_FIELD_1138, "desc": 'You see a grassy field.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_CHICKEN_COOP: {
        "name": 'A chicken coop',
        "desc": 'You stand inside a rather crowded chicken coop.  The cackle of hens fill\nthe air.  The only exit is to the south.',
        "exits": {
            "s": {"to": R_BARN, "desc": 'You see a large barn.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_GREEN_DRAGON: {
        "name": 'The Green Dragon',
        "desc": "Welcome to the Green Dragon, the undisputed leader in the art of\ninnkeeping.  A rather charming and friendly hostess stands to the side,\nready to offer you food and drink.  While most of the patrons are halfling\nlocals, you spy an occasional human or two.  As you listen more closely\nto the conversations that fill the inn, you hear the tales of great and\nseasoned adventurers as well as the usual gossip.  You feel as if you've\nfound your second home in the Green Dragon.  You see a stairway leading\nupwards.",
        "exits": {
            "w": {"to": R_DELVING_LANE, "desc": 'You see Delving Lane.'},
            "u": {"to": R_INN_OF_THE_GREEN_DRAGON, "desc": 'You see the reception.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_SHIRIFF_POST_OF_DELVING_LANE: {
        "name": 'Shiriff Post of Delving Lane',
        "desc": 'You are in the Shiriff Post which acts as the nucleus for the three shiriffs\nof Delving Lane.  As you examine the shiriffs on duty, you come to realize\nthat the halflings of the Shire are not to be reckoned with.  You cower with\nawe.  The only exit is to the west.',
        "exits": {
            "w": {"to": R_DELVING_LANE_1133, "desc": 'You see Delving Lane.'},
        },
        "flags": {"indoors": True},
        "sector": 'inside',
    },
    R_DARK_TUNNEL: {
        "name": 'A dark tunnel',
        "desc": 'You stand inside a small underground tunnel.  The ceiling is so low that\nyou must crouch to avoid hitting your head.  You see light from a small\nhole in the ceiling while to the east you see nothing but darkness.',
        "exits": {
            "e": {"to": R_DARK_TUNNEL_1147, "desc": 'You see a dark tunnel.'},
            "u": {"to": R_REAR_OF_WATERMILL, "desc": 'You see a portal which leads to a small room.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_DARK_TUNNEL_1147: {
        "name": 'A dark tunnel',
        "desc": 'You stand inside a small underground tunnel.  The ceiling is so low that\nyou must crouch to avoid hitting your head.  The tunnel continues east and\nwest.  All you can see is darkness.',
        "exits": {
            "e": {"to": R_DARK_TUNNEL_1148, "desc": 'You see a dark tunnel.'},
            "w": {"to": R_DARK_TUNNEL, "desc": 'You see a dark tunnel.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_DARK_TUNNEL_1148: {
        "name": 'A dark tunnel',
        "desc": 'You stand inside a small underground tunnel.  The ceiling is so low that\nyou must crouch to avoid hitting your head.  The tunnel continues east and\nwest.  All you can see is darkness.',
        "exits": {
            "e": {"to": R_THREE_WAY_INTERSECTION, "desc": 'You see a dark tunnel.'},
            "w": {"to": R_DARK_TUNNEL_1147, "desc": 'You see a dark tunnel.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_THREE_WAY_INTERSECTION: {
        "name": 'A three way intersection',
        "desc": 'You stand at an intersection.  The tunnel continues east and west while\nto the north you can barely make out a smaller trail.',
        "exits": {
            "n": {"to": R_DARK_TUNNEL_1151, "desc": 'You see a dark tunnel.'},
            "e": {"to": R_END_OF_A_DARK_TUNNEL, "desc": 'You see a dark tunnel.'},
            "w": {"to": R_DARK_TUNNEL_1148, "desc": 'You see a dark tunnel.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_END_OF_A_DARK_TUNNEL: {
        "name": 'End of a dark tunnel',
        "desc": 'You stand at the end of a dark tunnel.  The underground tunnel continues\nto the west.  From a trapdoor in the ceiling you can hear the din of\nadventurers.',
        "exits": {
            "w": {"to": R_THREE_WAY_INTERSECTION, "desc": 'You see a dark tunnel.'},
            "u": {"to": 3001, "desc": 'You hear the din of adventurers.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_DARK_TUNNEL_1151: {
        "name": 'A dark tunnel',
        "desc": 'You stand inside a small underground tunnel.  The ceiling is so low that\nyou must crouch to avoid hitting your head.  The tunnel continues north and\nsouth.  To the west you see a Shirriff Post while to the east lies a small\nhome.  All you can see is darkness.',
        "exits": {
            "n": {"to": R_DARK_TUNNEL_1152, "desc": 'You see a dark tunnel.'},
            "e": {"to": R_HALFLING_HOLE, "desc": 'You see a halfling hole.'},
            "s": {"to": R_THREE_WAY_INTERSECTION, "desc": 'You see a dark tunnel.'},
            "w": {"to": R_SHIRIFF_POST_OF_THE_LOWER_SHIRE, "desc": "Above a great oak door you see a sign which reads 'Shirriff Post'."},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_DARK_TUNNEL_1152: {
        "name": 'A dark tunnel',
        "desc": 'You stand inside a small underground tunnel.  The ceiling is so low that\nyou must crouch to avoid hitting your head.  The tunnel continues north and\nsouth.  To the west lies a small home.  All you can see is darkness.',
        "exits": {
            "n": {"to": R_END_OF_A_DARK_TUNNEL_1156, "desc": 'You see a dark tunnel.'},
            "s": {"to": R_DARK_TUNNEL_1151, "desc": 'You see a dark tunnel.'},
            "w": {"to": R_HALFLING_HOLE_1155, "desc": 'You see a halfling hole.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_SHIRIFF_POST_OF_THE_LOWER_SHIRE: {
        "name": 'Shiriff Post of the Lower Shire',
        "desc": 'You are in the shiriff Post which acts as the nucleus for the three shiriffs\nof the Lower Shire.  As you examine the shiriffs on duty, you come to realize\nthat the halflings of the Shire are not to be reckoned with.  You cower with\nawe.  The only exit is to the east.',
        "exits": {
            "e": {"to": R_DARK_TUNNEL_1151, "desc": 'You see a dark tunnel.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_HALFLING_HOLE: {
        "name": 'A halfling hole',
        "desc": "You stand inside a rather crudely built halfling hole.  The many passageways\nand winding paths remind you of a rodent's lair.  The air is musty and damp\nand you feel the need for fresh air.",
        "exits": {
            "w": {"to": R_DARK_TUNNEL_1151, "desc": 'You see a dark tunnel.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_HALFLING_HOLE_1155: {
        "name": 'A halfling hole',
        "desc": "You stand inside a rather crudely built halfling hole.  The many passageways\nand winding paths remind you of a rodent's lair.  The air is musty and damp\nand you feel the need for fresh air.",
        "exits": {
            "e": {"to": R_DARK_TUNNEL_1152, "desc": 'You see a dark tunnel.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_END_OF_A_DARK_TUNNEL_1156: {
        "name": 'End of a dark tunnel',
        "desc": 'You are at one end of a dark tunnel.  The tunnel continues to the south\nwhile on the ceiling you can make out a trapdoor.',
        "exits": {
            "s": {"to": R_DARK_TUNNEL_1152, "desc": 'You see a dark tunnel.'},
            "u": {"to": R_PANTRY, "desc": 'A trapdoor on the ceiling reveals a passageway.'},
        },
        "flags": {"dark": True, "indoors": True},
        "sector": 'inside',
    },
    R_INN_OF_THE_GREEN_DRAGON: {
        "name": 'The Inn of the Green Dragon',
        "desc": 'You are standing in the Inn of the Green dragon.  Large paintings of\nhalflings at work, and halflings at play adorn the walls.  Comfortable\nbenches and seats line the walls.  A stairway leads down.',
        "exits": {
            "d": R_GREEN_DRAGON,
        },
        "flags": {"indoors": True, "arena": True},
        "sector": 'inside',
    },
}

# -- Item templates -------------------------------------------------------------
OBJECTS = {
    I_RAINBOW_STAFF: {
        "keywords":    'rainbow staff',
        "short_descr": 'the rainbow staff',
        "description": 'The rainbow staff lies here.',
        "material":    'oldstyle',
        "type": 'light',
        "wear_flags": {"take": True},
        "extra_flags": {"magic": True},
        "stat_bonuses": {'wis': 1},
        "level": 5, "weight": 80, "value": 550,
    },
    I_STING: {
        "keywords":    'sting',
        "short_descr": 'sting',
        "description": 'Sting lies here.',
        "material":    'mithril',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "extra_flags": {"glow": True, "hum": True, "anti_evil": True},
        "weapon_type": 'dagger', "dam_type": 'bite', "dice": (2, 7, 0),
        "weapon_flags": {},
        "stat_bonuses": {'dex': 2},
        "level": 17, "weight": 10, "value": 3500,
    },
    I_SIGN: {
        "keywords":    'sign',
        "short_descr": 'a sign',
        "description": 'A sign demands your attention.',
        "material":    'oldstyle',
        "type": 'furniture',
        "wear_flags": {},
        "level": 0, "weight": 0, "value": 0,
        "extra_descs": [('sign', 'Welcome to the Shire.  As you enter the Shire from Haon-Dor you come under\nthe jurisdiction of the Thain, the peacekeeper of the Shire.  Consequently,\nby entering these lands you agree to obey our laws.  If you break these laws,\nyou will be severely punished.  We do not like riff raff in our peaceful\ntown.\n\n\t\t\t\t\tThe Thain\n\t\t\t\t\tPeacekeeper of the Shire')],
    },
    I_PIPEWEED_BREAD: {
        "keywords":    'pipeweed bread',
        "short_descr": 'a pipeweed bread',
        "description": 'A loaf of pipeweed bread arouses your hunger.',
        "material":    'oldstyle',
        "type": 'food',
        "wear_flags": {"take": True},
        "food_hours": 30, "food_hunger": 24,
        "level": 0, "weight": 10, "value": 15,
    },
    I_SILVERY_CLOAK: {
        "keywords":    'silvery cloak',
        "short_descr": 'a silvery cloak',
        "description": 'A silvery cloak lies here.',
        "material":    'oldstyle',
        "type": 'armor',
        "wear_flags": {"take": True, "about": True},
        "extra_flags": {"magic": True, "anti_evil": True},
        "armor": (6, 6, 6, 2),
        "stat_bonuses": {'saves': -1},
        "level": 15, "weight": 30, "value": 1320,
    },
    I_ONE_RING: {
        "keywords":    'one ring',
        "short_descr": 'the One Ring',
        "description": 'The One Ring is here.',
        "material":    'oldstyle',
        "type": 'jewelry',
        "wear_flags": {"take": True, "finger": True},
        "extra_flags": {"magic": True},
        "level": 20, "weight": 30, "value": 1660,
    },
    I_ELVEN_SPEAR: {
        "keywords":    'elven spear',
        "short_descr": 'an elven spear',
        "description": 'An elven spear lies here.',
        "material":    'wood',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "extra_flags": {"hum": True, "magic": True, "anti_evil": True},
        "weapon_type": 'staff', "dam_type": 'thrust', "dice": (2, 8, 0),
        "weapon_flags": {},
        "stat_bonuses": {'hitroll': 2},
        "level": 16, "weight": 50, "value": 500,
    },
    I_MITHRIL_AXE: {
        "keywords":    'mithril axe',
        "short_descr": 'a mithril axe',
        "description": 'A mithril axe lies here.',
        "material":    'mithril',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "extra_flags": {"glow": True, "dark": True, "noremove": True, "nopurge": True},
        "weapon_type": 'axe', "dam_type": 'chop', "dice": (2, 8, 0),
        "weapon_flags": {},
        "stat_bonuses": {'damroll': 2},
        "level": 17, "weight": 120, "value": 1440,
    },
    I_THAIN_GIRTH: {
        "keywords":    'thain girth',
        "short_descr": 'the thain girth',
        "description": 'The girth of the thain lies here.',
        "material":    'oldstyle',
        "type": 'armor',
        "wear_flags": {"take": True, "waist": True},
        "armor": (5, 5, 5, 0),
        "stat_bonuses": {'wis': 2},
        "level": 17, "weight": 40, "value": 3600,
    },
    I_TINY_DAGGER: {
        "keywords":    'tiny dagger',
        "short_descr": 'a tiny dagger',
        "description": 'A tiny dagger lies here.',
        "material":    'oldstyle',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "weapon_type": 'dagger', "dam_type": 'pierce', "dice": (1, 6, 0),
        "weapon_flags": {},
        "level": 1, "weight": 30, "value": 230,
    },
    I_EGG: {
        "keywords":    'egg',
        "short_descr": 'an egg',
        "description": 'An egg lies here.',
        "material":    'oldstyle',
        "type": 'food',
        "wear_flags": {"take": True},
        "food_hours": 12, "food_hunger": 12,
        "level": 0, "weight": 10, "value": 2,
    },
    I_BAG: {
        "keywords":    'bag',
        "short_descr": 'a bag',
        "description": 'A bag is on the floor.',
        "material":    'oldstyle',
        "type": 'container',
        "wear_flags": {"take": True},
        "container_max_weight": 50,
        "container_flags": {},
        "level": 0, "weight": 10, "value": 11,
    },
    I_LANTERN: {
        "keywords":    'lantern',
        "short_descr": 'a lantern',
        "description": 'A lantern is on the floor.',
        "material":    'oldstyle',
        "type": 'light',
        "wear_flags": {"take": True},
        "level": 0, "weight": 40, "value": 60,
    },
    I_BARDICHE: {
        "keywords":    'bardiche',
        "short_descr": 'a bardiche',
        "description": 'A long weapon with a sharp end is on the floor.',
        "material":    'wood',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "weapon_type": 'polearm', "dam_type": 'cleave', "dice": (2, 11, 0),
        "weapon_flags": {"two_hands": True},
        "stat_bonuses": {'hitroll': 4},
        "level": 21, "weight": 100, "value": 1810,
    },
    I_FLAIL: {
        "keywords":    'flail',
        "short_descr": 'a flail',
        "description": 'A flail is on the floor.',
        "material":    'iron',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "weapon_type": 'flail', "dam_type": 'smash', "dice": (2, 4, 0),
        "weapon_flags": {},
        "level": 5, "weight": 80, "value": 390,
    },
    I_WOODEN_BARDICHE: {
        "keywords":    'wooden bardiche',
        "short_descr": 'a wooden bardiche',
        "description": 'A long weapon with a wooden blade is on the floor.',
        "material":    'wood',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "weapon_type": 'polearm', "dam_type": 'pound', "dice": (2, 3, 0),
        "weapon_flags": {"two_hands": True},
        "stat_bonuses": {'hitroll': 4},
        "level": 3, "weight": 100, "value": 980,
    },
    I_DAGGER_SHIRIFF: {
        "keywords":    'dagger shiriff',
        "short_descr": "a shiriff's dagger",
        "description": 'A tiny but very sharp dagger lies here.',
        "material":    'steel',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "weapon_type": 'dagger', "dam_type": 'pierce', "dice": (2, 4, 0),
        "weapon_flags": {},
        "stat_bonuses": {'damroll': 1, 'hitroll': 1},
        "level": 6, "weight": 10, "value": 480,
    },
    I_CLUB_HEAVY: {
        "keywords":    'club heavy',
        "short_descr": "the Thain's club",
        "description": 'You see see a heavy club. Looks just right for whomping heads.',
        "material":    'wood',
        "type": 'weapon',
        "wear_flags": {"take": True, "wield": True},
        "weapon_type": 'mace', "dam_type": 'pound', "dice": (2, 7, 0),
        "weapon_flags": {},
        "level": 12, "weight": 30, "value": 620,
    },
}

# -- Resets ---------------------------------------------------------------------
# ("M", mob_vnum, global_limit, room_vnum, room_limit) -- spawn mob up to limits
# ("O", item_vnum, room_vnum)                          -- place one item copy in room
# ("E", item_vnum, slot_name)                          -- equip item on last M mob
# ("G", item_vnum)                                     -- give item to last M mob inventory
# ("P", item_vnum, limit, container_vnum, max)         -- [PRIMESUD] deferred: no containers
# ("R", room_vnum, num_dirs)                           -- [PRIMESUD] deferred: unused in current areas
# D resets are baked into room exit flags at conversion time
RESETS = (
    ("O", I_SIGN, R_ENTRANCE_TO_THE_SHIRE),
    ("M", M_OLDSTYLE_SHOPKEEPER, 1, R_GENERAL_STORE, 1),
    ("G", I_BAG),
    ("G", I_LANTERN),
    ("M", M_OLDSTYLE_BLACKSMITH, 1, R_HOUSE_OF_ARMS, 1),
    ("M", M_OLDSTYLE_NURSEMAID, 2, R_KID_N_KEEP, 2),
    ("M", M_OLDSTYLE_NURSEMAID, 2, R_KID_N_KEEP, 2),
    ("M", M_OLDSTYLE_TODDLER, 6, R_KID_N_KEEP, 6),
    ("M", M_OLDSTYLE_TODDLER, 6, R_KID_N_KEEP, 6),
    ("M", M_OLDSTYLE_TODDLER, 6, R_KID_N_KEEP, 6),
    ("M", M_OLDSTYLE_TODDLER, 6, R_KID_N_KEEP, 6),
    ("M", M_OLDSTYLE_TODDLER, 6, R_KID_N_KEEP, 6),
    ("M", M_OLDSTYLE_TODDLER, 6, R_KID_N_KEEP, 6),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE, 2),
    ("E", I_DAGGER_SHIRIFF, "wield"),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE, 2),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF_1111, 4, R_SHIRIFF_POST_OF_THE_EASTERN_SHIRE, 1),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_THAIN, 1, R_THAIN_S_OFFICE, 1),
    ("E", I_CLUB_HEAVY, "wield"),
    ("E", 616, "body"),
    ("E", I_THAIN_GIRTH, "waist"),
    ("M", M_OLDSTYLE_COUNTRY_BUMPKIN, 4, R_SMIAL, 1),
    ("G", I_PIPEWEED_BREAD),
    ("M", M_OLDSTYLE_COUNTRY_BUMPKIN, 4, R_SMIAL_1115, 1),
    ("G", I_PIPEWEED_BREAD),
    ("M", M_OLDSTYLE_INNKEEPER, 1, R_IVY_BUSH, 1),
    ("G", I_EGG),
    ("G", 648),
    ("G", 649),
    ("G", 650),
    ("M", M_OLDSTYLE_SEASONED_ADVENTURER, 5, R_IVY_BUSH, 2),
    ("M", M_OLDSTYLE_SEASONED_ADVENTURER, 5, R_IVY_BUSH, 2),
    ("M", M_OLDSTYLE_LOCAL_GOSSIP, 2, R_IVY_BUSH, 2),
    ("M", M_OLDSTYLE_LOCAL_GOSSIP, 2, R_IVY_BUSH, 2),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_IVY_BUSH, 3),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_IVY_BUSH, 3),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_IVY_BUSH, 3),
    ("M", M_OLDSTYLE_BATTLE_MASTER, 1, R_SHIRIFF_TRAINING_GROUNDS, 1),
    ("E", I_BARDICHE, "wield"),
    ("M", M_OLDSTYLE_TRAINEE, 3, R_SHIRIFF_TRAINING_GROUNDS, 3),
    ("E", I_WOODEN_BARDICHE, "wield"),
    ("M", M_OLDSTYLE_TRAINEE, 3, R_SHIRIFF_TRAINING_GROUNDS, 3),
    ("E", I_WOODEN_BARDICHE, "wield"),
    ("M", M_OLDSTYLE_TRAINEE, 3, R_SHIRIFF_TRAINING_GROUNDS, 3),
    ("E", I_WOODEN_BARDICHE, "wield"),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_THE_BRIDGE, 2),
    ("E", I_DAGGER_SHIRIFF, "wield"),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_THE_BRIDGE, 2),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF_1111, 4, R_SHIRIFF_POST_OF_THE_BRIDGE, 1),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_GROCER, 1, R_GROCER_S_DELIGHT, 1),
    ("G", I_PIPEWEED_BREAD),
    ("M", M_OLDSTYLE_MILL_WORKER, 6, R_ENTRANCE_TO_WATERMILL, 6),
    ("M", M_OLDSTYLE_MILL_WORKER, 6, R_ENTRANCE_TO_WATERMILL, 6),
    ("M", M_OLDSTYLE_MILL_WORKER, 6, R_WATERMILL, 6),
    ("M", M_OLDSTYLE_MILL_WORKER, 6, R_WATERMILL, 6),
    ("M", M_OLDSTYLE_MILL_WORKER, 6, R_WATERMILL, 6),
    ("M", M_OLDSTYLE_MILLER, 1, R_WATERMILL, 1),
    ("M", M_OLDSTYLE_MILL_WORKER, 6, R_REAR_OF_WATERMILL, 6),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_NORTHERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_NORTHERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_NORTHERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_SOUTHERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_SOUTHERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_SOUTHERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_WESTERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_WESTERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_YOUTH, 9, R_WESTERN_END_OF_GRASSY_FIELD, 3),
    ("M", M_OLDSTYLE_HALFLING_BEAUTY, 1, R_GRASSY_FIELD, 1),
    ("M", M_OLDSTYLE_ELVEN_WIZARD, 1, R_GRASSY_FIELD, 1),
    ("E", I_SILVERY_CLOAK, "about"),
    ("E", I_RAINBOW_STAFF, "light"),
    ("M", M_OLDSTYLE_ELVEN_WARRIOR, 1, R_BEDROOM, 1),
    ("E", I_ELVEN_SPEAR, "wield"),
    ("E", 622, "head"),
    ("M", M_OLDSTYLE_DWARVEN_PRINCE, 1, R_BEDROOM, 1),
    ("E", I_MITHRIL_AXE, "wield"),
    ("E", 621, "body"),
    ("M", M_OLDSTYLE_RING_KEEPER, 1, R_PANTRY, 1),
    ("E", I_STING, "wield"),
    ("E", I_ONE_RING, "finger_l"),
    ("E", 623, "legs"),
    ("M", M_OLDSTYLE_BULL, 1, R_GRASSY_FIELD_1138, 1),
    ("M", M_OLDSTYLE_PIG, 5, R_PIG_PEN, 5),
    ("M", M_OLDSTYLE_PIG, 5, R_PIG_PEN, 5),
    ("M", M_OLDSTYLE_PIG, 5, R_PIG_PEN, 5),
    ("M", M_OLDSTYLE_PIG, 5, R_PIG_PEN, 5),
    ("M", M_OLDSTYLE_PIG, 5, R_PIG_PEN, 5),
    ("M", M_OLDSTYLE_FARMER_GAMGEE, 1, R_GAMGEE_RESIDENCE, 1),
    ("M", M_OLDSTYLE_COW, 3, R_BARN, 3),
    ("M", M_OLDSTYLE_COW, 3, R_BARN, 3),
    ("M", M_OLDSTYLE_COW, 3, R_BARN, 3),
    ("M", M_OLDSTYLE_HORSE, 4, R_BARN, 4),
    ("M", M_OLDSTYLE_HORSE, 4, R_BARN, 4),
    ("M", M_OLDSTYLE_HORSE, 4, R_BARN, 4),
    ("M", M_OLDSTYLE_HORSE, 4, R_BARN, 4),
    ("M", M_OLDSTYLE_CHICKEN, 6, R_CHICKEN_COOP, 6),
    ("G", I_EGG),
    ("M", M_OLDSTYLE_CHICKEN, 6, R_CHICKEN_COOP, 6),
    ("G", I_EGG),
    ("M", M_OLDSTYLE_CHICKEN, 6, R_CHICKEN_COOP, 6),
    ("G", I_EGG),
    ("M", M_OLDSTYLE_CHICKEN, 6, R_CHICKEN_COOP, 6),
    ("G", I_EGG),
    ("M", M_OLDSTYLE_CHICKEN, 6, R_CHICKEN_COOP, 6),
    ("G", I_EGG),
    ("M", M_OLDSTYLE_CHICKEN, 6, R_CHICKEN_COOP, 6),
    ("G", I_EGG),
    ("M", M_OLDSTYLE_INNKEEPER_1130, 1, R_GREEN_DRAGON, 1),
    ("G", I_EGG),
    ("G", 648),
    ("G", 649),
    ("G", 650),
    ("M", M_OLDSTYLE_RECEPTIONIST, 1, R_INN_OF_THE_GREEN_DRAGON, 1),
    ("M", M_OLDSTYLE_SEASONED_ADVENTURER, 5, R_GREEN_DRAGON, 3),
    ("M", M_OLDSTYLE_SEASONED_ADVENTURER, 5, R_GREEN_DRAGON, 3),
    ("M", M_OLDSTYLE_SEASONED_ADVENTURER, 5, R_GREEN_DRAGON, 3),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_GREEN_DRAGON, 4),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_GREEN_DRAGON, 4),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_GREEN_DRAGON, 4),
    ("M", M_OLDSTYLE_CHIC_URBANITE, 7, R_GREEN_DRAGON, 4),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_DELVING_LANE, 2),
    ("E", I_DAGGER_SHIRIFF, "wield"),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_DELVING_LANE, 2),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF_1111, 4, R_SHIRIFF_POST_OF_DELVING_LANE, 1),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_THE_LOWER_SHIRE, 2),
    ("E", I_DAGGER_SHIRIFF, "wield"),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF, 8, R_SHIRIFF_POST_OF_THE_LOWER_SHIRE, 2),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_SHIRIFF_1111, 4, R_SHIRIFF_POST_OF_THE_LOWER_SHIRE, 1),
    ("E", 616, "body"),
    ("M", M_OLDSTYLE_COUNTRY_BUMPKIN, 4, R_HALFLING_HOLE, 1),
    ("M", M_OLDSTYLE_COUNTRY_BUMPKIN, 4, R_HALFLING_HOLE_1155, 1),
)

# -- Shops ---------------------------------------------------------------------
# keeper_vnum: mob that runs the shop
# buy_types: item type names the shop will purchase
# profit_buy/profit_sell: percentage markup/markdown
SHOPS = (
    {"keeper": M_OLDSTYLE_INNKEEPER, "buy_types": ['drink'], "profit_buy": 150, "profit_sell": 50, "open_hour": 0, "close_hour": 23},
    {"keeper": M_OLDSTYLE_SHOPKEEPER, "buy_types": ['trash', 'weapon', 'container', 'light', 'drink'], "profit_buy": 150, "profit_sell": 50, "open_hour": 0, "close_hour": 23},
    {"keeper": M_OLDSTYLE_GROCER, "buy_types": ['trash', 'weapon', 'container', 'light', 'drink'], "profit_buy": 150, "profit_sell": 50, "open_hour": 0, "close_hour": 23},
    {"keeper": M_OLDSTYLE_BLACKSMITH, "buy_types": ['armor', 'weapon'], "profit_buy": 150, "profit_sell": 50, "open_hour": 0, "close_hour": 23},
    {"keeper": M_OLDSTYLE_INNKEEPER_1130, "buy_types": ['drink'], "profit_buy": 150, "profit_sell": 50, "open_hour": 0, "close_hour": 23},
)

# -- Helps ---------------------------------------------------------------------
HELPS = (
)

# -- Socials -------------------------------------------------------------------
SOCIALS = (
)

# -- MobProgs ------------------------------------------------------------------
# (vnum, code) -- mob program code blocks, referenced by mob triggers
MOBPROGS = {
}
