# fmt: off
# Generated from 1stMud 4.5.3 skills.dat -- do not edit manually.
# Re-generate: uv run python tools/skills_to_primesud.py reference/1stMud4.5.3/data/skills.dat

# skill_level / rating indices:  0=Mage  1=Cleric  2=Thief  3=Warrior  4=Paladin  5=Ranger
# skill_level 53 = ANGEL (not available to that class)  52 = LEVEL_IMMORTAL (immo-only)
# rating 0 = class cannot learn this skill individually

# -- GSN constants --------------------------------------------------------------
GSN_BLINDNESS                  = 5
GSN_CHARM_PERSON               = 15
GSN_CURSE                      = 30
GSN_FLY                        = 51
GSN_INVIS                      = 63
GSN_MASS_INVIS                 = 69
GSN_PLAGUE                     = 72
GSN_POISON                     = 73
GSN_SANCTUARY                  = 81
GSN_SLEEP                      = 84
GSN_AXE                        = 99
GSN_DAGGER                     = 100
GSN_FLAIL                      = 101
GSN_MACE                       = 102
GSN_POLEARM                    = 103
GSN_SHIELD_BLOCK               = 104
GSN_SPEAR                      = 105
GSN_SWORD                      = 106
GSN_WHIP                       = 107
GSN_BACKSTAB                   = 108
GSN_BASH                       = 109
GSN_BERSERK                    = 110
GSN_DIRT                       = 111
GSN_DISARM                     = 112
GSN_DODGE                      = 113
GSN_ENHANCED_DAMAGE            = 114
GSN_ENVENOM                    = 115
GSN_HAND_TO_HAND               = 116
GSN_KICK                       = 117
GSN_PARRY                      = 118
GSN_RESCUE                     = 119
GSN_TRIP                       = 120
GSN_SECOND_ATTACK              = 121
GSN_THIRD_ATTACK               = 122
GSN_FAST_HEALING               = 123
GSN_HAGGLE                     = 124
GSN_HIDE                       = 125
GSN_LORE                       = 126
GSN_MEDITATION                 = 127
GSN_PEEK                       = 128
GSN_HUNT                       = 129
GSN_PICK_LOCK                  = 130
GSN_SNEAK                      = 131
GSN_STEAL                      = 132
GSN_SCROLLS                    = 133
GSN_STAVES                     = 134
GSN_WANDS                      = 135
GSN_RECALL                     = 136

# -- SKILL_TABLE ----------------------------------------------------------------
SKILL_TABLE = [
    (  0, {  # sn 0
        "name":        'reserved',
        "skill_level": (53, 53, 53, 53, 53, 53),
        "rating":      (999, 999, 999, 999, 999, 999),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '',
        "msg_obj":     '',
    }),
    (  1, {  # sn 1
        "name":        'trivia pill',
        "skill_level": (53, 53, 53, 53, 53, 53),
        "rating":      (0, 0, 0, 0, 0, 0),
        "spell_fun":   'spell_trivia_pill',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       18,
        "noun_damage": '',
        "msg_off":     '!Trivia Pill!',
        "msg_obj":     '',
    }),
    (  2, {  # sn 2
        "name":        'acid blast',
        "skill_level": (28, 53, 35, 32, 53, 32),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_acid_blast',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'acid blast',
        "msg_off":     '!Acid Blast!',
        "msg_obj":     '',
    }),
    (  3, {  # sn 3
        "name":        'armor',
        "skill_level": (7, 2, 10, 5, 2, 5),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_armor',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel less armored.',
        "msg_obj":     '',
    }),
    (  4, {  # sn 4
        "name":        'bless',
        "skill_level": (53, 7, 53, 8, 7, 8),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_bless',
        "target":      'obj_char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel less righteous.',
        "msg_obj":     "$p's holy aura fades.",
    }),
    (  5, {  # sn 5  GSN_BLINDNESS
        "name":        'blindness',
        "skill_level": (12, 8, 17, 15, 8, 15),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_blindness',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        GSN_BLINDNESS,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You can see again.',
        "msg_obj":     '',
    }),
    (  6, {  # sn 6
        "name":        'burning hands',
        "skill_level": (7, 53, 10, 9, 53, 9),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_burning_hands',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'burning hands',
        "msg_off":     '!Burning Hands!',
        "msg_obj":     '',
    }),
    (  7, {  # sn 7
        "name":        'call lightning',
        "skill_level": (26, 18, 31, 22, 18, 22),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_call_lightning',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'lightning bolt',
        "msg_off":     '!Call Lightning!',
        "msg_obj":     '',
    }),
    (  8, {  # sn 8
        "name":        'calm',
        "skill_level": (48, 16, 50, 20, 16, 20),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_calm',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    30,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You have lost your peace of mind.',
        "msg_obj":     '',
    }),
    (  9, {  # sn 9
        "name":        'cancellation',
        "skill_level": (18, 26, 34, 34, 26, 34),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cancellation',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": '!cancellation!',
        "msg_off":     '',
        "msg_obj":     '',
    }),
    ( 10, {  # sn 10
        "name":        'cause critical',
        "skill_level": (53, 13, 53, 19, 13, 19),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cause_critical',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'spell',
        "msg_off":     '!Cause Critical!',
        "msg_obj":     '',
    }),
    ( 11, {  # sn 11
        "name":        'cause light',
        "skill_level": (53, 1, 53, 3, 1, 3),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cause_light',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'spell',
        "msg_off":     '!Cause Light!',
        "msg_obj":     '',
    }),
    ( 12, {  # sn 12
        "name":        'cause serious',
        "skill_level": (53, 7, 53, 10, 7, 10),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cause_serious',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    17,
        "beats":       12,
        "noun_damage": 'spell',
        "msg_off":     '!Cause Serious!',
        "msg_obj":     '',
    }),
    ( 13, {  # sn 13
        "name":        'chain lightning',
        "skill_level": (33, 53, 39, 36, 53, 36),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_chain_lightning',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    25,
        "beats":       12,
        "noun_damage": 'lightning',
        "msg_off":     '!Chain Lightning!',
        "msg_obj":     '',
    }),
    ( 14, {  # sn 14
        "name":        'change sex',
        "skill_level": (53, 53, 53, 53, 53, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_change_sex',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'Your body feels familiar again.',
        "msg_obj":     '',
    }),
    ( 15, {  # sn 15  GSN_CHARM_PERSON
        "name":        'charm person',
        "skill_level": (20, 53, 25, 53, 53, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_charm_person',
        "target":      'char_offensive',
        "min_pos":     'standing',
        "pgsn":        GSN_CHARM_PERSON,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel more self-confident.',
        "msg_obj":     '',
    }),
    ( 16, {  # sn 16
        "name":        'chill touch',
        "skill_level": (4, 53, 6, 6, 53, 6),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_chill_touch',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'chilling touch',
        "msg_off":     'You feel less cold.',
        "msg_obj":     '',
    }),
    ( 17, {  # sn 17
        "name":        'color spray',
        "skill_level": (16, 53, 22, 20, 53, 20),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_color_spray',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'colour spray',
        "msg_off":     '!Colour Spray!',
        "msg_obj":     '',
    }),
    ( 18, {  # sn 18
        "name":        'continual light',
        "skill_level": (6, 4, 6, 9, 4, 9),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_continual_light',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    7,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Continual Light!',
        "msg_obj":     '',
    }),
    ( 19, {  # sn 19
        "name":        'control weather',
        "skill_level": (15, 19, 28, 22, 19, 22),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_control_weather',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    25,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Control Weather!',
        "msg_obj":     '',
    }),
    ( 20, {  # sn 20
        "name":        'create food',
        "skill_level": (10, 5, 11, 12, 5, 12),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_create_food',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Create Food!',
        "msg_obj":     '',
    }),
    ( 21, {  # sn 21
        "name":        'create rose',
        "skill_level": (16, 11, 10, 24, 11, 24),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_create_rose',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    30,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Create Rose!',
        "msg_obj":     '',
    }),
    ( 22, {  # sn 22
        "name":        'create spring',
        "skill_level": (14, 17, 23, 20, 17, 20),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_create_spring',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Create Spring!',
        "msg_obj":     '',
    }),
    ( 23, {  # sn 23
        "name":        'create water',
        "skill_level": (8, 3, 12, 11, 3, 11),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_create_water',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Create Water!',
        "msg_obj":     '',
    }),
    ( 24, {  # sn 24
        "name":        'cure blindness',
        "skill_level": (53, 6, 53, 8, 6, 8),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cure_blindness',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Cure Blindness!',
        "msg_obj":     '',
    }),
    ( 25, {  # sn 25
        "name":        'cure critical',
        "skill_level": (53, 13, 53, 19, 13, 19),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cure_critical',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Cure Critical!',
        "msg_obj":     '',
    }),
    ( 26, {  # sn 26
        "name":        'cure disease',
        "skill_level": (53, 13, 53, 14, 13, 14),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cure_disease',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Cure Disease!',
        "msg_obj":     '',
    }),
    ( 27, {  # sn 27
        "name":        'cure light',
        "skill_level": (53, 1, 53, 3, 1, 3),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cure_light',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    10,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Cure Light!',
        "msg_obj":     '',
    }),
    ( 28, {  # sn 28
        "name":        'cure poison',
        "skill_level": (53, 14, 53, 16, 14, 16),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cure_poison',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Cure Poison!',
        "msg_obj":     '',
    }),
    ( 29, {  # sn 29
        "name":        'cure serious',
        "skill_level": (53, 7, 53, 10, 7, 10),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_cure_serious',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Cure Serious!',
        "msg_obj":     '',
    }),
    ( 30, {  # sn 30  GSN_CURSE
        "name":        'curse',
        "skill_level": (18, 18, 26, 22, 18, 22),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_curse',
        "target":      'obj_char_offensive',
        "min_pos":     'fighting',
        "pgsn":        GSN_CURSE,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'curse',
        "msg_off":     'The curse wears off.',
        "msg_obj":     '$p is no longer impure.',
    }),
    ( 31, {  # sn 31
        "name":        'demonfire',
        "skill_level": (53, 34, 53, 45, 34, 45),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_demonfire',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'torments',
        "msg_off":     '!Demonfire!',
        "msg_obj":     '',
    }),
    ( 32, {  # sn 32
        "name":        'detect evil',
        "skill_level": (11, 4, 12, 53, 4, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_detect_evil',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'The red in your vision disappears.',
        "msg_obj":     '',
    }),
    ( 33, {  # sn 33
        "name":        'detect good',
        "skill_level": (11, 4, 12, 53, 4, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_detect_good',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'The gold in your vision disappears.',
        "msg_obj":     '',
    }),
    ( 34, {  # sn 34
        "name":        'detect hidden',
        "skill_level": (15, 11, 12, 53, 11, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_detect_hidden',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel less aware of your surroundings.',
        "msg_obj":     '',
    }),
    ( 35, {  # sn 35
        "name":        'detect invis',
        "skill_level": (3, 8, 6, 53, 8, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_detect_invis',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You no longer see invisible objects.',
        "msg_obj":     '',
    }),
    ( 36, {  # sn 36
        "name":        'detect magic',
        "skill_level": (2, 6, 5, 53, 6, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_detect_magic',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'The detect magic wears off.',
        "msg_obj":     '',
    }),
    ( 37, {  # sn 37
        "name":        'detect poison',
        "skill_level": (15, 7, 9, 53, 7, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_detect_poison',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Detect Poison!',
        "msg_obj":     '',
    }),
    ( 38, {  # sn 38
        "name":        'dispel evil',
        "skill_level": (53, 15, 53, 21, 15, 21),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_dispel_evil',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'dispel evil',
        "msg_off":     '!Dispel Evil!',
        "msg_obj":     '',
    }),
    ( 39, {  # sn 39
        "name":        'dispel good',
        "skill_level": (53, 15, 53, 21, 15, 21),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_dispel_good',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'dispel good',
        "msg_off":     '!Dispel Good!',
        "msg_obj":     '',
    }),
    ( 40, {  # sn 40
        "name":        'dispel magic',
        "skill_level": (16, 24, 30, 30, 24, 30),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_dispel_magic',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Dispel Magic!',
        "msg_obj":     '',
    }),
    ( 41, {  # sn 41
        "name":        'earthquake',
        "skill_level": (53, 10, 53, 14, 10, 14),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_earthquake',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'earthquake',
        "msg_off":     '!Earthquake!',
        "msg_obj":     '',
    }),
    ( 42, {  # sn 42
        "name":        'enchant armor',
        "skill_level": (16, 53, 53, 53, 53, 53),
        "rating":      (2, 2, 4, 4, 2, 4),
        "spell_fun":   'spell_enchant_armor',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Enchant Armor!',
        "msg_obj":     '',
    }),
    ( 43, {  # sn 43
        "name":        'enchant weapon',
        "skill_level": (17, 53, 53, 53, 53, 53),
        "rating":      (2, 2, 4, 4, 2, 4),
        "spell_fun":   'spell_enchant_weapon',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Enchant Weapon!',
        "msg_obj":     '',
    }),
    ( 44, {  # sn 44
        "name":        'energy drain',
        "skill_level": (19, 22, 26, 23, 22, 23),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_energy_drain',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    35,
        "beats":       12,
        "noun_damage": 'energy drain',
        "msg_off":     '!Energy Drain!',
        "msg_obj":     '',
    }),
    ( 45, {  # sn 45
        "name":        'faerie fire',
        "skill_level": (6, 3, 5, 8, 3, 8),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_faerie_fire',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": 'faerie fire',
        "msg_off":     'The pink aura around you fades away.',
        "msg_obj":     '',
    }),
    ( 46, {  # sn 46
        "name":        'faerie fog',
        "skill_level": (14, 21, 16, 24, 21, 24),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_faerie_fog',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    12,
        "beats":       12,
        "noun_damage": 'faerie fog',
        "msg_off":     '!Faerie Fog!',
        "msg_obj":     '',
    }),
    ( 47, {  # sn 47
        "name":        'farsight',
        "skill_level": (14, 16, 16, 53, 16, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_farsight',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    36,
        "beats":       20,
        "noun_damage": 'farsight',
        "msg_off":     '!Farsight!',
        "msg_obj":     '',
    }),
    ( 48, {  # sn 48
        "name":        'fireball',
        "skill_level": (22, 53, 30, 26, 53, 26),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_fireball',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'fireball',
        "msg_off":     '!Fireball!',
        "msg_obj":     '',
    }),
    ( 49, {  # sn 49
        "name":        'fireproof',
        "skill_level": (13, 12, 19, 18, 12, 18),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_fireproof',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    10,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '',
        "msg_obj":     "$p's protective aura fades.",
    }),
    ( 50, {  # sn 50
        "name":        'flamestrike',
        "skill_level": (53, 20, 53, 27, 20, 27),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_flamestrike',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'flamestrike',
        "msg_off":     '!Flamestrike!',
        "msg_obj":     '',
    }),
    ( 51, {  # sn 51  GSN_FLY
        "name":        'fly',
        "skill_level": (10, 18, 20, 22, 18, 22),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_fly',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        GSN_FLY,
        "min_mana":    10,
        "beats":       18,
        "noun_damage": '',
        "msg_off":     'You slowly float to the ground.',
        "msg_obj":     '',
    }),
    ( 52, {  # sn 52
        "name":        'floating disc',
        "skill_level": (4, 10, 7, 16, 10, 16),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_floating_disc',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    40,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Floating disc!',
        "msg_obj":     '',
    }),
    ( 53, {  # sn 53
        "name":        'frenzy',
        "skill_level": (53, 24, 53, 26, 24, 26),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_frenzy',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    30,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     'Your rage ebbs.',
        "msg_obj":     '',
    }),
    ( 54, {  # sn 54
        "name":        'gate',
        "skill_level": (27, 17, 32, 28, 17, 28),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_gate',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    80,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Gate!',
        "msg_obj":     '',
    }),
    ( 55, {  # sn 55
        "name":        'giant strength',
        "skill_level": (11, 53, 22, 20, 53, 20),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_giant_strength',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel weaker.',
        "msg_obj":     '',
    }),
    ( 56, {  # sn 56
        "name":        'harm',
        "skill_level": (53, 23, 53, 28, 23, 28),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_harm',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    35,
        "beats":       12,
        "noun_damage": 'harm spell',
        "msg_off":     '!Harm!',
        "msg_obj":     '',
    }),
    ( 57, {  # sn 57
        "name":        'haste',
        "skill_level": (21, 53, 26, 29, 53, 29),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_haste',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    30,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel yourself slow down.',
        "msg_obj":     '',
    }),
    ( 58, {  # sn 58
        "name":        'heal',
        "skill_level": (53, 21, 33, 30, 21, 30),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_heal',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    50,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Heal!',
        "msg_obj":     '',
    }),
    ( 59, {  # sn 59
        "name":        'heat metal',
        "skill_level": (53, 16, 53, 23, 16, 23),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_heat_metal',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    25,
        "beats":       18,
        "noun_damage": 'spell',
        "msg_off":     '!Heat Metal!',
        "msg_obj":     '',
    }),
    ( 60, {  # sn 60
        "name":        'holy word',
        "skill_level": (53, 36, 53, 42, 36, 42),
        "rating":      (2, 2, 4, 4, 2, 4),
        "spell_fun":   'spell_holy_word',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    200,
        "beats":       24,
        "noun_damage": 'divine wrath',
        "msg_off":     '!Holy Word!',
        "msg_obj":     '',
    }),
    ( 61, {  # sn 61
        "name":        'identify',
        "skill_level": (15, 16, 18, 53, 16, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_identify',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    12,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Identify!',
        "msg_obj":     '',
    }),
    ( 62, {  # sn 62
        "name":        'infravision',
        "skill_level": (9, 13, 10, 16, 13, 16),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_infravision',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       18,
        "noun_damage": '',
        "msg_off":     'You no longer see in the dark.',
        "msg_obj":     '',
    }),
    ( 63, {  # sn 63  GSN_INVIS
        "name":        'invisibility',
        "skill_level": (5, 53, 9, 53, 53, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_invis',
        "target":      'obj_char_defensive',
        "min_pos":     'standing',
        "pgsn":        GSN_INVIS,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You are no longer invisible.',
        "msg_obj":     '$p fades into view.',
    }),
    ( 64, {  # sn 64
        "name":        'know alignment',
        "skill_level": (12, 9, 20, 53, 9, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_know_alignment',
        "target":      'char_defensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    9,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Know Alignment!',
        "msg_obj":     '',
    }),
    ( 65, {  # sn 65
        "name":        'lightning bolt',
        "skill_level": (13, 23, 18, 16, 23, 16),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_lightning_bolt',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'lightning bolt',
        "msg_off":     '!Lightning Bolt!',
        "msg_obj":     '',
    }),
    ( 66, {  # sn 66
        "name":        'locate object',
        "skill_level": (9, 15, 11, 53, 15, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_locate_object',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       18,
        "noun_damage": '',
        "msg_off":     '!Locate Object!',
        "msg_obj":     '',
    }),
    ( 67, {  # sn 67
        "name":        'magic missile',
        "skill_level": (1, 53, 2, 2, 53, 2),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_magic_missile',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'magic missile',
        "msg_off":     '!Magic Missile!',
        "msg_obj":     '',
    }),
    ( 68, {  # sn 68
        "name":        'mass healing',
        "skill_level": (53, 38, 53, 46, 38, 46),
        "rating":      (2, 2, 4, 4, 2, 4),
        "spell_fun":   'spell_mass_healing',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       36,
        "noun_damage": '',
        "msg_off":     '!Mass Healing!',
        "msg_obj":     '',
    }),
    ( 69, {  # sn 69  GSN_MASS_INVIS
        "name":        'mass invis',
        "skill_level": (22, 25, 31, 53, 25, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_mass_invis',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_MASS_INVIS,
        "min_mana":    20,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     'You are no longer invisible.',
        "msg_obj":     '',
    }),
    ( 70, {  # sn 70
        "name":        'nexus',
        "skill_level": (40, 35, 50, 45, 35, 45),
        "rating":      (2, 2, 4, 4, 2, 4),
        "spell_fun":   'spell_nexus',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    150,
        "beats":       36,
        "noun_damage": '',
        "msg_off":     '!Nexus!',
        "msg_obj":     '',
    }),
    ( 71, {  # sn 71
        "name":        'pass door',
        "skill_level": (24, 32, 25, 37, 32, 37),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_pass_door',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel solid again.',
        "msg_obj":     '',
    }),
    ( 72, {  # sn 72  GSN_PLAGUE
        "name":        'plague',
        "skill_level": (23, 17, 36, 26, 17, 26),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_plague',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        GSN_PLAGUE,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'sickness',
        "msg_off":     'Your sores vanish.',
        "msg_obj":     '',
    }),
    ( 73, {  # sn 73  GSN_POISON
        "name":        'poison',
        "skill_level": (17, 12, 15, 21, 12, 21),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_poison',
        "target":      'obj_char_offensive',
        "min_pos":     'fighting',
        "pgsn":        GSN_POISON,
        "min_mana":    10,
        "beats":       12,
        "noun_damage": 'poison',
        "msg_off":     'You feel less sick.',
        "msg_obj":     'The poison on $p dries up.',
    }),
    ( 74, {  # sn 74
        "name":        'portal',
        "skill_level": (35, 30, 45, 40, 30, 40),
        "rating":      (2, 2, 4, 4, 2, 4),
        "spell_fun":   'spell_portal',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Portal!',
        "msg_obj":     '',
    }),
    ( 75, {  # sn 75
        "name":        'protection evil',
        "skill_level": (12, 9, 17, 11, 9, 11),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_protection_evil',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel less protected.',
        "msg_obj":     '',
    }),
    ( 76, {  # sn 76
        "name":        'protection good',
        "skill_level": (12, 9, 17, 11, 9, 11),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_protection_good',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel less protected.',
        "msg_obj":     '',
    }),
    ( 77, {  # sn 77
        "name":        'ray of truth',
        "skill_level": (53, 35, 53, 47, 35, 47),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_ray_of_truth',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'ray of truth',
        "msg_off":     '!Ray of Truth!',
        "msg_obj":     '',
    }),
    ( 78, {  # sn 78
        "name":        'recharge',
        "skill_level": (9, 53, 53, 53, 53, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_recharge',
        "target":      'obj_inventory',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    60,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Recharge!',
        "msg_obj":     '',
    }),
    ( 79, {  # sn 79
        "name":        'refresh',
        "skill_level": (8, 5, 12, 9, 5, 9),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_refresh',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    12,
        "beats":       18,
        "noun_damage": 'refresh',
        "msg_off":     '!Refresh!',
        "msg_obj":     '',
    }),
    ( 80, {  # sn 80
        "name":        'remove curse',
        "skill_level": (53, 18, 53, 22, 18, 22),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_remove_curse',
        "target":      'obj_char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Remove Curse!',
        "msg_obj":     '',
    }),
    ( 81, {  # sn 81  GSN_SANCTUARY
        "name":        'sanctuary',
        "skill_level": (36, 20, 42, 30, 20, 30),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_sanctuary',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        GSN_SANCTUARY,
        "min_mana":    75,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'The white aura around your body fades.',
        "msg_obj":     '',
    }),
    ( 82, {  # sn 82
        "name":        'shield',
        "skill_level": (20, 35, 35, 40, 35, 40),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_shield',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    12,
        "beats":       18,
        "noun_damage": '',
        "msg_off":     'Your force shield shimmers then fades away.',
        "msg_obj":     '',
    }),
    ( 83, {  # sn 83
        "name":        'shocking grasp',
        "skill_level": (10, 53, 14, 13, 53, 13),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_shocking_grasp',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": 'shocking grasp',
        "msg_off":     '!Shocking Grasp!',
        "msg_obj":     '',
    }),
    ( 84, {  # sn 84  GSN_SLEEP
        "name":        'sleep',
        "skill_level": (10, 53, 11, 53, 53, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_sleep',
        "target":      'char_offensive',
        "min_pos":     'standing',
        "pgsn":        GSN_SLEEP,
        "min_mana":    15,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel less tired.',
        "msg_obj":     '',
    }),
    ( 85, {  # sn 85
        "name":        'slow',
        "skill_level": (23, 30, 29, 32, 30, 32),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_slow',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    30,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You feel yourself speed up.',
        "msg_obj":     '',
    }),
    ( 86, {  # sn 86
        "name":        'stone skin',
        "skill_level": (25, 40, 40, 45, 40, 45),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_stone_skin',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    12,
        "beats":       18,
        "noun_damage": '',
        "msg_off":     'Your skin feels soft again.',
        "msg_obj":     '',
    }),
    ( 87, {  # sn 87
        "name":        'summon',
        "skill_level": (24, 12, 29, 22, 12, 22),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_summon',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    50,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Summon!',
        "msg_obj":     '',
    }),
    ( 88, {  # sn 88
        "name":        'teleport',
        "skill_level": (13, 22, 25, 36, 22, 36),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_teleport',
        "target":      'char_self',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    35,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Teleport!',
        "msg_obj":     '',
    }),
    ( 89, {  # sn 89
        "name":        'ventriloquate',
        "skill_level": (1, 53, 2, 53, 53, 53),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_ventriloquate',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Ventriloquate!',
        "msg_obj":     '',
    }),
    ( 90, {  # sn 90
        "name":        'weaken',
        "skill_level": (11, 14, 16, 17, 14, 17),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_weaken',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'spell',
        "msg_off":     'You feel stronger.',
        "msg_obj":     '',
    }),
    ( 91, {  # sn 91
        "name":        'word of recall',
        "skill_level": (32, 28, 40, 30, 28, 30),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_word_of_recall',
        "target":      'char_self',
        "min_pos":     'resting',
        "pgsn":        None,
        "min_mana":    5,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Word of Recall!',
        "msg_obj":     '',
    }),
    ( 92, {  # sn 92
        "name":        'acid breath',
        "skill_level": (31, 32, 33, 34, 32, 34),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_acid_breath',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       24,
        "noun_damage": 'blast of acid',
        "msg_off":     '!Acid Breath!',
        "msg_obj":     '',
    }),
    ( 93, {  # sn 93
        "name":        'fire breath',
        "skill_level": (40, 45, 50, 51, 45, 51),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_fire_breath',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    200,
        "beats":       24,
        "noun_damage": 'blast of flame',
        "msg_off":     'The smoke leaves your eyes.',
        "msg_obj":     '',
    }),
    ( 94, {  # sn 94
        "name":        'frost breath',
        "skill_level": (34, 36, 38, 40, 36, 40),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_frost_breath',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    125,
        "beats":       24,
        "noun_damage": 'blast of frost',
        "msg_off":     '!Frost Breath!',
        "msg_obj":     '',
    }),
    ( 95, {  # sn 95
        "name":        'gas breath',
        "skill_level": (39, 43, 47, 50, 43, 50),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_gas_breath',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    175,
        "beats":       24,
        "noun_damage": 'blast of gas',
        "msg_off":     '!Gas Breath!',
        "msg_obj":     '',
    }),
    ( 96, {  # sn 96
        "name":        'lightning breath',
        "skill_level": (37, 40, 43, 46, 40, 46),
        "rating":      (1, 1, 2, 2, 1, 2),
        "spell_fun":   'spell_lightning_breath',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    150,
        "beats":       24,
        "noun_damage": 'blast of lightning',
        "msg_off":     '!Lightning Breath!',
        "msg_obj":     '',
    }),
    ( 97, {  # sn 97
        "name":        'general purpose',
        "skill_level": (53, 53, 53, 53, 53, 53),
        "rating":      (0, 0, 0, 0, 0, 0),
        "spell_fun":   'spell_general_purpose',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": 'general purpose ammo',
        "msg_off":     '!General Purpose Ammo!',
        "msg_obj":     '',
    }),
    ( 98, {  # sn 98
        "name":        'high explosive',
        "skill_level": (53, 53, 53, 53, 53, 53),
        "rating":      (0, 0, 0, 0, 0, 0),
        "spell_fun":   'spell_high_explosive',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        None,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": 'high explosive ammo',
        "msg_off":     '!High Explosive Ammo!',
        "msg_obj":     '',
    }),
    ( 99, {  # sn 99  GSN_AXE
        "name":        'axe',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (6, 6, 5, 4, 6, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_AXE,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Axe!',
        "msg_obj":     '',
    }),
    (100, {  # sn 100  GSN_DAGGER
        "name":        'dagger',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (2, 3, 2, 2, 3, 2),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_DAGGER,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Dagger!',
        "msg_obj":     '',
    }),
    (101, {  # sn 101  GSN_FLAIL
        "name":        'flail',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (6, 3, 6, 4, 3, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_FLAIL,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Flail!',
        "msg_obj":     '',
    }),
    (102, {  # sn 102  GSN_MACE
        "name":        'mace',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (5, 2, 3, 3, 2, 3),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_MACE,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Mace!',
        "msg_obj":     '',
    }),
    (103, {  # sn 103  GSN_POLEARM
        "name":        'polearm',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (6, 6, 6, 4, 6, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_POLEARM,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Polearm!',
        "msg_obj":     '',
    }),
    (104, {  # sn 104  GSN_SHIELD_BLOCK
        "name":        'shield block',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (6, 4, 6, 2, 4, 2),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_SHIELD_BLOCK,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Shield!',
        "msg_obj":     '',
    }),
    (105, {  # sn 105  GSN_SPEAR
        "name":        'spear',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (4, 4, 4, 3, 4, 3),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_SPEAR,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Spear!',
        "msg_obj":     '',
    }),
    (106, {  # sn 106  GSN_SWORD
        "name":        'sword',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (5, 6, 3, 2, 6, 2),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_SWORD,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!sword!',
        "msg_obj":     '',
    }),
    (107, {  # sn 107  GSN_WHIP
        "name":        'whip',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (6, 5, 5, 4, 5, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_WHIP,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Whip!',
        "msg_obj":     '',
    }),
    (108, {  # sn 108  GSN_BACKSTAB
        "name":        'backstab',
        "skill_level": (53, 53, 1, 53, 53, 53),
        "rating":      (0, 0, 5, 0, 0, 0),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_BACKSTAB,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": 'backstab',
        "msg_off":     '!Backstab!',
        "msg_obj":     '',
    }),
    (109, {  # sn 109  GSN_BASH
        "name":        'bash',
        "skill_level": (53, 53, 53, 1, 53, 1),
        "rating":      (0, 0, 0, 4, 0, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_BASH,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": 'bash',
        "msg_off":     '!Bash!',
        "msg_obj":     '',
    }),
    (110, {  # sn 110  GSN_BERSERK
        "name":        'berserk',
        "skill_level": (53, 53, 53, 18, 53, 18),
        "rating":      (0, 0, 0, 5, 0, 5),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_BERSERK,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     'You feel your pulse slow down.',
        "msg_obj":     '',
    }),
    (111, {  # sn 111  GSN_DIRT
        "name":        'dirt kicking',
        "skill_level": (53, 53, 3, 3, 53, 3),
        "rating":      (0, 0, 4, 4, 0, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_DIRT,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": 'kicked dirt',
        "msg_off":     'You rub the dirt out of your eyes.',
        "msg_obj":     '',
    }),
    (112, {  # sn 112  GSN_DISARM
        "name":        'disarm',
        "skill_level": (53, 53, 12, 11, 53, 11),
        "rating":      (0, 0, 6, 4, 0, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_DISARM,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Disarm!',
        "msg_obj":     '',
    }),
    (113, {  # sn 113  GSN_DODGE
        "name":        'dodge',
        "skill_level": (20, 22, 1, 13, 22, 13),
        "rating":      (8, 8, 4, 6, 8, 6),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_DODGE,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Dodge!',
        "msg_obj":     '',
    }),
    (114, {  # sn 114  GSN_ENHANCED_DAMAGE
        "name":        'enhanced damage',
        "skill_level": (45, 30, 25, 1, 30, 1),
        "rating":      (10, 9, 5, 3, 9, 3),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_ENHANCED_DAMAGE,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Enhanced Damage!',
        "msg_obj":     '',
    }),
    (115, {  # sn 115  GSN_ENVENOM
        "name":        'envenom',
        "skill_level": (53, 53, 10, 53, 53, 53),
        "rating":      (0, 0, 4, 0, 0, 0),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'resting',
        "pgsn":        GSN_ENVENOM,
        "min_mana":    0,
        "beats":       36,
        "noun_damage": '',
        "msg_off":     '!Envenom!',
        "msg_obj":     '',
    }),
    (116, {  # sn 116  GSN_HAND_TO_HAND
        "name":        'hand to hand',
        "skill_level": (25, 10, 15, 6, 10, 6),
        "rating":      (8, 5, 6, 4, 5, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_HAND_TO_HAND,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Hand to Hand!',
        "msg_obj":     '',
    }),
    (117, {  # sn 117  GSN_KICK
        "name":        'kick',
        "skill_level": (53, 12, 14, 8, 12, 8),
        "rating":      (0, 4, 6, 3, 4, 3),
        "spell_fun":   'spell_null',
        "target":      'char_offensive',
        "min_pos":     'fighting',
        "pgsn":        GSN_KICK,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": 'kick',
        "msg_off":     '!Kick!',
        "msg_obj":     '',
    }),
    (118, {  # sn 118  GSN_PARRY
        "name":        'parry',
        "skill_level": (22, 20, 13, 1, 20, 1),
        "rating":      (8, 8, 6, 4, 8, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_PARRY,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Parry!',
        "msg_obj":     '',
    }),
    (119, {  # sn 119  GSN_RESCUE
        "name":        'rescue',
        "skill_level": (53, 53, 53, 1, 53, 1),
        "rating":      (0, 0, 0, 4, 0, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_RESCUE,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Rescue!',
        "msg_obj":     '',
    }),
    (120, {  # sn 120  GSN_TRIP
        "name":        'trip',
        "skill_level": (53, 53, 1, 15, 53, 15),
        "rating":      (0, 0, 4, 8, 0, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_TRIP,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": 'trip',
        "msg_off":     '!Trip!',
        "msg_obj":     '',
    }),
    (121, {  # sn 121  GSN_SECOND_ATTACK
        "name":        'second attack',
        "skill_level": (30, 24, 12, 5, 24, 5),
        "rating":      (10, 8, 5, 3, 8, 3),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_SECOND_ATTACK,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Second Attack!',
        "msg_obj":     '',
    }),
    (122, {  # sn 122  GSN_THIRD_ATTACK
        "name":        'third attack',
        "skill_level": (53, 53, 24, 12, 53, 12),
        "rating":      (0, 0, 10, 4, 0, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'fighting',
        "pgsn":        GSN_THIRD_ATTACK,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Third Attack!',
        "msg_obj":     '',
    }),
    (123, {  # sn 123  GSN_FAST_HEALING
        "name":        'fast healing',
        "skill_level": (15, 9, 16, 6, 9, 6),
        "rating":      (8, 5, 6, 4, 5, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'sleeping',
        "pgsn":        GSN_FAST_HEALING,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Fast Healing!',
        "msg_obj":     '',
    }),
    (124, {  # sn 124  GSN_HAGGLE
        "name":        'haggle',
        "skill_level": (7, 18, 1, 14, 18, 14),
        "rating":      (5, 8, 3, 6, 8, 6),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'resting',
        "pgsn":        GSN_HAGGLE,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Haggle!',
        "msg_obj":     '',
    }),
    (125, {  # sn 125  GSN_HIDE
        "name":        'hide',
        "skill_level": (53, 53, 1, 12, 53, 12),
        "rating":      (0, 0, 4, 6, 0, 6),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'resting',
        "pgsn":        GSN_HIDE,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Hide!',
        "msg_obj":     '',
    }),
    (126, {  # sn 126  GSN_LORE
        "name":        'lore',
        "skill_level": (10, 10, 6, 20, 10, 20),
        "rating":      (6, 6, 4, 8, 6, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'resting',
        "pgsn":        GSN_LORE,
        "min_mana":    0,
        "beats":       36,
        "noun_damage": '',
        "msg_off":     '!Lore!',
        "msg_obj":     '',
    }),
    (127, {  # sn 127  GSN_MEDITATION
        "name":        'meditation',
        "skill_level": (6, 6, 15, 15, 6, 15),
        "rating":      (5, 5, 8, 8, 5, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'sleeping',
        "pgsn":        GSN_MEDITATION,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     'Meditation',
        "msg_obj":     '',
    }),
    (128, {  # sn 128  GSN_PEEK
        "name":        'peek',
        "skill_level": (8, 21, 1, 14, 21, 14),
        "rating":      (5, 7, 3, 6, 7, 6),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_PEEK,
        "min_mana":    0,
        "beats":       0,
        "noun_damage": '',
        "msg_off":     '!Peek!',
        "msg_obj":     '',
    }),
    (129, {  # sn 129  GSN_HUNT
        "name":        'hunt',
        "skill_level": (53, 53, 25, 40, 53, 25),
        "rating":      (0, 0, 6, 5, 0, 4),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_HUNT,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Hunt!',
        "msg_obj":     '',
    }),
    (130, {  # sn 130  GSN_PICK_LOCK
        "name":        'pick lock',
        "skill_level": (25, 25, 7, 25, 25, 25),
        "rating":      (8, 8, 4, 8, 8, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_PICK_LOCK,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Pick!',
        "msg_obj":     '',
    }),
    (131, {  # sn 131  GSN_SNEAK
        "name":        'sneak',
        "skill_level": (53, 53, 4, 10, 53, 10),
        "rating":      (0, 0, 4, 6, 0, 6),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_SNEAK,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     'You no longer feel stealthy.',
        "msg_obj":     '',
    }),
    (132, {  # sn 132  GSN_STEAL
        "name":        'steal',
        "skill_level": (53, 53, 5, 53, 53, 53),
        "rating":      (0, 0, 4, 0, 0, 0),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_STEAL,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Steal!',
        "msg_obj":     '',
    }),
    (133, {  # sn 133  GSN_SCROLLS
        "name":        'scrolls',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (2, 3, 5, 8, 3, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_SCROLLS,
        "min_mana":    0,
        "beats":       24,
        "noun_damage": '',
        "msg_off":     '!Scrolls!',
        "msg_obj":     '',
    }),
    (134, {  # sn 134  GSN_STAVES
        "name":        'staves',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (2, 3, 5, 8, 3, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_STAVES,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Staves!',
        "msg_obj":     '',
    }),
    (135, {  # sn 135  GSN_WANDS
        "name":        'wands',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (2, 3, 5, 8, 3, 8),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_WANDS,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Wands!',
        "msg_obj":     '',
    }),
    (136, {  # sn 136  GSN_RECALL
        "name":        'recall',
        "skill_level": (1, 1, 1, 1, 1, 1),
        "rating":      (2, 2, 2, 2, 2, 2),
        "spell_fun":   'spell_null',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        GSN_RECALL,
        "min_mana":    0,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '!Recall!',
        "msg_obj":     '',
    }),
    (137, {  # sn 137
        "name":        'forceshield',
        "skill_level": (30, 30, 54, 54, 51, 54),
        "rating":      (4, 4, 5, 5, 5, 5),
        "spell_fun":   'spell_forceshield',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       14,
        "noun_damage": 'force shield',
        "msg_off":     'The force shield about you fades away.',
        "msg_obj":     '',
    }),
    (138, {  # sn 138
        "name":        'staticshield',
        "skill_level": (30, 35, 54, 54, 54, 41),
        "rating":      (4, 4, 5, 5, 5, 5),
        "spell_fun":   'spell_staticshield',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       14,
        "noun_damage": 'static shield',
        "msg_off":     'The static around you grounds out.',
        "msg_obj":     '',
    }),
    (139, {  # sn 139
        "name":        'flameshield',
        "skill_level": (25, 37, 54, 54, 54, 54),
        "rating":      (4, 4, 5, 5, 5, 5),
        "spell_fun":   'spell_flameshield',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       14,
        "noun_damage": 'flame shield',
        "msg_off":     'The flames surrounding you die.',
        "msg_obj":     '',
    }),
    (140, {  # sn 140
        "name":        'channel',
        "skill_level": (54, 38, 54, 54, 54, 54),
        "rating":      (5, 4, 5, 5, 5, 5),
        "spell_fun":   'spell_channel',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    50,
        "beats":       12,
        "noun_damage": '!channel!',
        "msg_off":     '',
        "msg_obj":     '',
    }),
    (141, {  # sn 141
        "name":        'investiture',
        "skill_level": (29, 30, 54, 54, 54, 54),
        "rating":      (4, 4, 4, 4, 4, 4),
        "spell_fun":   'spell_investiture',
        "target":      'char_self',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    50,
        "beats":       12,
        "noun_damage": '',
        "msg_off":     '',
        "msg_obj":     '',
    }),
    (142, {  # sn 142
        "name":        'powerstorm',
        "skill_level": (46, 46, 54, 54, 52, 50),
        "rating":      (5, 5, 5, 5, 5, 5),
        "spell_fun":   'spell_powerstorm',
        "target":      'ignore',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    100,
        "beats":       14,
        "noun_damage": 'power storm',
        "msg_off":     'The pain from a magical storm leaves you.',
        "msg_obj":     '',
    }),
    (143, {  # sn 143
        "name":        'mana burn',
        "skill_level": (25, 24, 54, 54, 54, 54),
        "rating":      (4, 4, 4, 4, 4, 4),
        "spell_fun":   'spell_mana_burn',
        "target":      'char_offensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       12,
        "noun_damage": 'mana burn',
        "msg_off":     'Your mana burns heal.',
        "msg_obj":     '',
    }),
    (144, {  # sn 144
        "name":        'bark skin',
        "skill_level": (50, 47, 54, 52, 52, 34),
        "rating":      (4, 4, 4, 4, 0, 4),
        "spell_fun":   'spell_bark_skin',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    22,
        "beats":       12,
        "noun_damage": '!bark skin!',
        "msg_off":     'You notice the layer of magical bark is no longer covering your skin.',
        "msg_obj":     '',
    }),
    (145, {  # sn 145
        "name":        'spell mantle',
        "skill_level": (14, 15, 54, 54, 20, 20),
        "rating":      (4, 4, 4, 4, 4, 4),
        "spell_fun":   'spell_spell_mantle',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    18,
        "beats":       12,
        "noun_damage": '!spell mantle!',
        "msg_off":     'The intensity of your spell mantle disappears.',
        "msg_obj":     '',
    }),
    (146, {  # sn 146
        "name":        'animal instinct',
        "skill_level": (18, 16, 54, 54, 24, 14),
        "rating":      (4, 4, 4, 4, 4, 4),
        "spell_fun":   'spell_animal_instinct',
        "target":      'char_defensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    20,
        "beats":       14,
        "noun_damage": '!animal instinct!',
        "msg_off":     'Your heightened animal instincts disappear.',
        "msg_obj":     '',
    }),
    (147, {  # sn 147
        "name":        'chaos flare',
        "skill_level": (23, 25, 54, 54, 54, 54),
        "rating":      (4, 4, 4, 4, 4, 4),
        "spell_fun":   'spell_chaos_flare',
        "target":      'char_offensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    30,
        "beats":       14,
        "noun_damage": 'chaos flare',
        "msg_off":     '',
        "msg_obj":     '',
    }),
    (148, {  # sn 148
        "name":        'wild magic',
        "skill_level": (23, 27, 54, 54, 53, 43),
        "rating":      (4, 4, 4, 4, 4, 4),
        "spell_fun":   'spell_wild_magic',
        "target":      'char_offensive',
        "min_pos":     'standing',
        "pgsn":        None,
        "min_mana":    25,
        "beats":       12,
        "noun_damage": 'wild magic',
        "msg_off":     '',
        "msg_obj":     '',
    }),
]
