"""Type stubs for the HP Prime arith module."""

def asc(c: str) -> int: ...
def char(n: int) -> str: ...
def euler(n: int) -> int: ...
def gcd(a: int, b: int) -> int: ...
def iegcd(a: int, b: int) -> tuple[int, int, int]: ...
def ifactor(n: int) -> list[int]: ...
def isprime(n: int) -> bool: ...
def lcm(a: int, b: int) -> int: ...
def nextprime(n: int) -> int: ...
def nprimes(n: int) -> int: ...
def prevprime(n: int) -> int: ...
