"""Type stubs for the HP Prime graphic module."""

from typing import Sequence

black: int
white: int
red: int
green: int
blue: int
cyan: int
magenta: int
yellow: int

def clear_screen() -> None: ...
def show() -> None: ...
def show_screen() -> None: ...
def draw_pixel(x: int, y: int, c: int) -> None: ...
def set_pixel(x: int, y: int, c: int) -> None: ...
def get_pixel(x: int, y: int) -> int: ...
def draw_line(x1: int, y1: int, x2: int, y2: int, c: int) -> None: ...
def draw_rectangle(x1: int, y1: int, x2: int, y2: int, c: int) -> None: ...
def draw_circle(x: int, y: int, r: int, c: int) -> None: ...
def draw_filled_circle(x: int, y: int, r: int, c: int) -> None: ...
def draw_arc(x: int, y: int, r: int, a1: float, a2: float, c: int) -> None: ...
def draw_filled_arc(x: int, y: int, r: int, a1: float, a2: float, c: int) -> None: ...
def draw_string(x: int, y: int, text: str, c: int, bg: int) -> None: ...
def draw_polygon(pts: Sequence[Sequence[int]], c: int) -> None: ...
def draw_filled_polygon(pts: Sequence[Sequence[int]], c: int) -> None: ...
