"""Type stubs for the HP Prime linalg module."""

from typing import Any, Sequence

def matrix(data: Sequence) -> Any: ...
def eye(n: int) -> Any: ...
def identity(n: int) -> Any: ...
def idn(n: int) -> Any: ...
def zeros(shape: Any) -> Any: ...
def ones(shape: Any) -> Any: ...
def inv(m: Any) -> Any: ...
def det(m: Any) -> float: ...
def transpose(m: Any) -> Any: ...
def dot(a: Any, b: Any) -> Any: ...
def cross(a: Any, b: Any) -> Any: ...
def solve(a: Any, b: Any) -> Any: ...
def eig(m: Any) -> Any: ...
def eigenvects(m: Any) -> Any: ...
def rref(m: Any) -> Any: ...
def fft(v: Any) -> Any: ...
def ifft(v: Any) -> Any: ...
def linspace(a: float, b: float, n: int) -> Any: ...
def arange(start: float, stop: float, step: float = ...) -> Any: ...
def rand() -> float: ...
def ranm(r: int, c: int) -> Any: ...
def ranv(n: int) -> Any: ...
def add(a: Any, b: Any) -> Any: ...
def sub(a: Any, b: Any) -> Any: ...
def mul(a: Any, b: Any) -> Any: ...
def abs(m: Any) -> Any: ...
def real(m: Any) -> Any: ...
def imag(m: Any) -> Any: ...
def conj(m: Any) -> Any: ...
def shape(m: Any) -> tuple: ...
def size(m: Any) -> int: ...
def apply(m: Any, func: Any) -> Any: ...
def horner(coeffs: Any, x: float) -> float: ...
def pcoeff(roots: Any) -> Any: ...
def peval(coeffs: Any, x: float) -> float: ...
def proot(coeffs: Any) -> Any: ...
