"""Type stubs for the HP Prime ucollections module."""

from typing import Any, Iterable

def namedtuple(name: str, fields: Any) -> type: ...

class OrderedDict(dict):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class deque:
    def __init__(self, iterable: Iterable = ..., maxlen: int = ...) -> None: ...
    def append(self, x: Any) -> None: ...
    def appendleft(self, x: Any) -> None: ...
    def pop(self) -> Any: ...
    def popleft(self) -> Any: ...
