"""Type stubs for the HP Prime uhashlib module."""

class sha256:
    def __init__(self, data: bytes = ...) -> None: ...
    def update(self, data: bytes) -> None: ...
    def digest(self) -> bytes: ...
