"""Type stubs for the HP Prime uio module."""

from typing import Any

def open(name: str, mode: str = ...) -> Any: ...

class BytesIO:
    def __init__(self, data: bytes = ...) -> None: ...
    def read(self, n: int = ...) -> bytes: ...
    def write(self, b: bytes) -> int: ...
    def seek(self, pos: int) -> None: ...
    def tell(self) -> int: ...
    def close(self) -> None: ...

class StringIO:
    def __init__(self, s: str = ...) -> None: ...
    def read(self, n: int = ...) -> str: ...
    def write(self, s: str) -> int: ...
    def seek(self, pos: int) -> None: ...
    def tell(self) -> int: ...
    def getvalue(self) -> str: ...
    def close(self) -> None: ...

class FileIO:
    def __init__(self, name: str, mode: str = ...) -> None: ...
    def read(self, n: int = ...) -> bytes: ...
    def write(self, b: bytes) -> int: ...
    def close(self) -> None: ...

class TextIOWrapper:
    def __init__(self, stream: Any, encoding: str = ...) -> None: ...
    def read(self, n: int = ...) -> str: ...
    def write(self, s: str) -> int: ...
    def close(self) -> None: ...
