"""Type stubs for the HP Prime urandom module."""

def random() -> float: ...
def randint(a: int, b: int) -> int: ...
def randrange(start: int, stop: int = ..., step: int = ...) -> int: ...
def choice(seq: list) -> object: ...
def getrandbits(n: int) -> int: ...
def seed(n: int) -> None: ...
def uniform(a: float, b: float) -> float: ...
