"""Type stubs for the HP Prime ure (micro-regex) module."""

from typing import Any

def compile(pattern: str) -> Any: ...
def match(pattern: str, string: str) -> Any: ...
def search(pattern: str, string: str) -> Any: ...
