"""Type stubs for the HP Prime ustruct module."""

from typing import Any

def pack(fmt: str, *v: Any) -> bytes: ...
def pack_into(fmt: str, buf: bytearray, offset: int, *v: Any) -> None: ...
def unpack(fmt: str, data: bytes) -> tuple: ...
def unpack_from(fmt: str, data: bytes, offset: int = ...) -> tuple: ...
def calcsize(fmt: str) -> int: ...
