# fmt: off
"""Race table data decoded from 1stMud races.dat (cf. 1stMud race_table in data_table.c).

Each entry maps race name -> race defaults dict.  Flag dicts use the
same {flag_name: True} convention as PrimeSUD area mob templates.

Bit-position decoding derived from 1stMud bits.h BIT_A..BIT_fx defines
cross-referenced with tables.c flag table arrays.

"summary" entries are [PRIMESUD] one-liners for the chargen race picker
(1stMud shows a bare race list + 'help <race>')."""

# [PRIMESUD] Chargen display order for PC races (1stMud pc_race_table order).
# HP Prime dicts don't guarantee insertion order, so RACE_TABLE.items() can't
# be used for user-facing ordering (see docs/BUILTINS.md).
PC_RACE_ORDER = ("Human", "Elf", "Dwarf", "Giant", "Dragon", "Orc")

RACE_TABLE = {
    "Human": {
        "pc_race": True,
        "summary": "Balanced stats; highest training caps",
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {
            "biped": True,
            "edible": True,
            "mammal": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
        "class_mult": (100, 100, 100, 100, 100, 100, 100),  # XP multiplier per class (classes.class_mult)
        "points": 0,  # [not ported] chargen creation points
        "skills": [],
    },
    "Elf": {
        "pc_race": True,
        "summary": "Agile and wise; charm resist, iron vuln",
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"charm": True},
        "vuln": {"iron": True},
        "form":  {
            "biped": True,
            "edible": True,
            "mammal": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (12, 14, 13, 15, 11),
        "max_stats": (16, 20, 18, 21, 15),
        "size": "small",
        "class_mult": (100, 125, 100, 120, 125, 120, 100),  # XP multiplier per class (classes.class_mult)
        "points": 5,  # [not ported] chargen creation points
        "skills": ['sneak', 'hide'],
    },
    "Dwarf": {
        "pc_race": True,
        "summary": "Hardy; disease/poison resist, slow swim",
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"disease": True, "poison": True},
        "vuln": {"drowning": True},
        "form":  {
            "biped": True,
            "edible": True,
            "mammal": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (14, 12, 14, 10, 15),
        "max_stats": (20, 16, 19, 14, 21),
        "size": "medium",
        "class_mult": (150, 100, 125, 100, 100, 100, 125),  # XP multiplier per class (classes.class_mult)
        "points": 8,  # [not ported] chargen creation points
        "skills": ['berserk'],
    },
    "Giant": {
        "pc_race": True,
        "summary": "Raw power; cold/fire resist, shock vuln",
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {},
        "res":  {"cold": True, "fire": True},
        "vuln": {"lightning": True, "mental": True},
        "form":  {
            "biped": True,
            "edible": True,
            "mammal": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (16, 11, 13, 11, 14),
        "max_stats": (22, 15, 18, 15, 20),
        "size": "large",
        "class_mult": (200, 150, 150, 105, 150, 105, 120),  # XP multiplier per class (classes.class_mult)
        "points": 6,  # [not ported] chargen creation points
        "skills": ['bash', 'fast healing'],
    },
    "Dragon": {
        "pc_race": True,
        "summary": "Mighty flyer; costly to advance",
        "act":  {},
        "aff":  {"flying": True, "infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"bash": True, "charm": True, "fire": True},
        "vuln": {"cold": True, "pierce": True},
        "form":  {"dragon": True, "edible": True, "sentient": True},
        "parts": {
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "fangs": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "horns": True,
            "legs": True,
            "scales": True,
            "tail": True,
            "wings": True,
        },
        "stats":     (16, 13, 13, 10, 15),
        "max_stats": (22, 22, 22, 19, 22),
        "size": "huge",
        "class_mult": (200, 200, 200, 200, 200, 200, 200),  # XP multiplier per class (classes.class_mult)
        "points": 10,  # [not ported] chargen creation points
        "skills": [],
    },
    "Orc": {
        "pc_race": True,
        "summary": "Tough and wise; disease resist, light vuln",
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"disease": True},
        "vuln": {"light": True},
        "form":  {
            "biped": True,
            "cold_blood": True,
            "edible": True,
            "mammal": True,
            "poison": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "horns": True,
            "legs": True,
            "tusks": True,
        },
        "stats":     (16, 10, 11, 15, 14),
        "max_stats": (22, 18, 19, 22, 20),
        "size": "medium",
        "class_mult": (200, 200, 100, 100, 180, 130, 110),  # XP multiplier per class (classes.class_mult)
        "points": 7,  # [not ported] chargen creation points
        "skills": ['kick'],
    },
    "Bat": {
        "pc_race": False,
        "act":  {},
        "aff":  {"dark_vision": True, "flying": True},
        "off":  {"dodge": True, "fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {"light": True},
        "form":  {"animal": True, "edible": True, "mammal": True},
        "parts": {
            "brains": True,
            "ear": True,
            "eye": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
            "wings": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Bear": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {"berserk": True, "crush": True, "disarm": True},
        "imm":  {},
        "res":  {"bash": True, "cold": True},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Cat": {
        "pc_race": False,
        "act":  {},
        "aff":  {"dark_vision": True},
        "off":  {"dodge": True, "fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Centipede": {
        "pc_race": False,
        "act":  {},
        "aff":  {"dark_vision": True},
        "off":  {},
        "imm":  {},
        "res":  {"cold": True, "pierce": True},
        "vuln": {"bash": True},
        "form":  {
            "animal": True,
            "edible": True,
            "insect": True,
            "poison": True,
        },
        "parts": {"eye": True, "head": True, "legs": True},
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Dog": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {"fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Doll": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {
            "cold": True,
            "disease": True,
            "drowning": True,
            "holy": True,
            "mental": True,
            "negative": True,
            "poison": True,
        },
        "res":  {"bash": True, "light": True},
        "vuln": {
            "acid": True,
            "energy": True,
            "fire": True,
            "lightning": True,
            "slash": True,
        },
        "form":  {
            "biped": True,
            "cold_blood": True,
            "construct": True,
            "other": True,
        },
        "parts": {
            "arms": True,
            "eye": True,
            "feet": True,
            "hands": True,
            "head": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Fido": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {"assist_race": True, "dodge": True},
        "imm":  {},
        "res":  {},
        "vuln": {"magic": True},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Fox": {
        "pc_race": False,
        "act":  {},
        "aff":  {"dark_vision": True},
        "off":  {"dodge": True, "fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Goblin": {
        "pc_race": False,
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"disease": True},
        "vuln": {"magic": True},
        "form":  {
            "biped": True,
            "cold_blood": True,
            "edible": True,
            "mammal": True,
            "poison": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "horns": True,
            "legs": True,
            "tusks": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Hobgoblin": {
        "pc_race": False,
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"disease": True, "poison": True},
        "vuln": {},
        "form":  {
            "biped": True,
            "cold_blood": True,
            "edible": True,
            "mammal": True,
            "poison": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "horns": True,
            "legs": True,
            "tusks": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Kobold": {
        "pc_race": False,
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {},
        "imm":  {},
        "res":  {"poison": True},
        "vuln": {"magic": True},
        "form":  {
            "biped": True,
            "cold_blood": True,
            "edible": True,
            "mammal": True,
            "poison": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "horns": True,
            "legs": True,
            "tusks": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Lizard": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {},
        "res":  {"poison": True},
        "vuln": {"cold": True},
        "form":  {
            "animal": True,
            "cold_blood": True,
            "edible": True,
            "reptile": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
            "long_tongue": True,
            "tail": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Modron": {
        "pc_race": False,
        "act":  {},
        "aff":  {"infrared": True},
        "off":  {"assist_align": True, "assist_race": True},
        "imm":  {
            "charm": True,
            "disease": True,
            "holy": True,
            "mental": True,
            "negative": True,
        },
        "res":  {"acid": True, "cold": True, "fire": True},
        "vuln": {},
        "form":  {"sentient": True},
        "parts": {
            "arms": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "hands": True,
            "head": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Pig": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "brains": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
            "tail": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Rabbit": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {"dodge": True, "fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "brains": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "School monster": {
        "pc_race": False,
        "act":  {"noalign": True},
        "aff":  {},
        "off":  {},
        "imm":  {"charm": True, "summon": True},
        "res":  {},
        "vuln": {"magic": True},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
            "tail": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Snake": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {},
        "res":  {"poison": True},
        "vuln": {"cold": True},
        "form":  {
            "animal": True,
            "cold_blood": True,
            "edible": True,
            "reptile": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
            "long_tongue": True,
            "tail": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Song bird": {
        "pc_race": False,
        "act":  {},
        "aff":  {"flying": True},
        "off":  {"dodge": True, "fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "bird": True, "edible": True},
        "parts": {
            "brains": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
            "wings": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Troll": {
        "pc_race": False,
        "act":  {},
        "aff":  {"detect_hidden": True, "infrared": True, "regeneration": True},
        "off":  {"berserk": True},
        "imm":  {},
        "res":  {"bash": True, "charm": True},
        "vuln": {"acid": True, "fire": True},
        "form":  {
            "biped": True,
            "cold_blood": True,
            "edible": True,
            "mammal": True,
            "poison": True,
            "sentient": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "fingers": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "horns": True,
            "legs": True,
            "tusks": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Water fowl": {
        "pc_race": False,
        "act":  {},
        "aff":  {"flying": True, "swim": True},
        "off":  {},
        "imm":  {},
        "res":  {"drowning": True},
        "vuln": {},
        "form":  {"animal": True, "bird": True, "edible": True},
        "parts": {
            "brains": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
            "wings": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Wolf": {
        "pc_race": False,
        "act":  {},
        "aff":  {"dark_vision": True},
        "off":  {"dodge": True, "fast": True},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {"animal": True, "biped": True, "mammal": True},
        "parts": {
            "arms": True,
            "brains": True,
            "claws": True,
            "ear": True,
            "eye": True,
            "feet": True,
            "guts": True,
            "head": True,
            "heart": True,
            "legs": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Wyvern": {
        "pc_race": False,
        "act":  {},
        "aff":  {"detect_hidden": True, "detect_invis": True, "flying": True},
        "off":  {"bash": True, "dodge": True, "fast": True},
        "imm":  {"poison": True},
        "res":  {},
        "vuln": {"light": True},
        "form":  {
            "animal": True,
            "dragon": True,
            "edible": True,
            "poison": True,
        },
        "parts": {
            "arms": True,
            "brains": True,
            "ear": True,
            "eye": True,
            "fangs": True,
            "feet": True,
            "guts": True,
            "hands": True,
            "head": True,
            "heart": True,
            "legs": True,
            "scales": True,
            "tail": True,
        },
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
    "Unique": {
        "pc_race": False,
        "act":  {},
        "aff":  {},
        "off":  {},
        "imm":  {},
        "res":  {},
        "vuln": {},
        "form":  {},
        "parts": {},
        "stats":     (13, 13, 13, 13, 13),
        "max_stats": (18, 18, 18, 18, 18),
        "size": "medium",
    },
}


def race_lookup(name):
    """Look up a race by name (case-insensitive prefix match) (cf. 1stMud `race_lookup` in lookup.c).

    Args:
        name (str): Race name or prefix.

    Returns:
        dict or None: Race data dict, or None if no match.
    """
    if not name:
        return None
    nl = name.lower()
    # Exact match first
    for rn, rd in RACE_TABLE.items():
        if rn.lower() == nl:
            return rd
    # Prefix match
    for rn, rd in RACE_TABLE.items():
        if rn.lower().startswith(nl):
            return rd
    return None
